// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lms,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z007sclg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.380000,HLS_SYN_LAT=143,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=2,HLS_SYN_FF=3000,HLS_SYN_LUT=1473,HLS_VERSION=2018_3}" *)

module lms (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_V,
        y_V_ap_vld,
        xn_V,
        dn_V
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_pp1_stage0 = 6'd16;
parameter    ap_ST_fsm_state8 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] y_V;
output   y_V_ap_vld;
input  [13:0] xn_V;
input  [13:0] dn_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_V_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [13:0] xk_V_0;
reg   [15:0] wk_V_0;
reg   [15:0] wk_V_1;
reg   [15:0] wk_V_2;
reg   [15:0] wk_V_3;
reg   [15:0] wk_V_4;
reg   [15:0] wk_V_5;
reg   [15:0] wk_V_6;
reg   [15:0] wk_V_7;
reg   [13:0] xk_V_1;
reg   [13:0] xk_V_2;
reg   [13:0] xk_V_3;
reg   [13:0] xk_V_4;
reg   [13:0] xk_V_5;
reg   [13:0] xk_V_6;
reg   [13:0] xk_V_7;
reg   [13:0] xk_V_63;
reg   [13:0] xk_V_8;
reg   [13:0] xk_V_9;
reg   [13:0] xk_V_10;
reg   [13:0] xk_V_11;
reg   [13:0] xk_V_12;
reg   [13:0] xk_V_13;
reg   [13:0] xk_V_14;
reg   [13:0] xk_V_15;
reg   [13:0] xk_V_16;
reg   [13:0] xk_V_17;
reg   [13:0] xk_V_18;
reg   [13:0] xk_V_19;
reg   [13:0] xk_V_20;
reg   [13:0] xk_V_21;
reg   [13:0] xk_V_22;
reg   [13:0] xk_V_23;
reg   [13:0] xk_V_24;
reg   [13:0] xk_V_25;
reg   [13:0] xk_V_26;
reg   [13:0] xk_V_27;
reg   [13:0] xk_V_28;
reg   [13:0] xk_V_29;
reg   [13:0] xk_V_30;
reg   [13:0] xk_V_31;
reg   [13:0] xk_V_32;
reg   [13:0] xk_V_33;
reg   [13:0] xk_V_34;
reg   [13:0] xk_V_35;
reg   [13:0] xk_V_36;
reg   [13:0] xk_V_37;
reg   [13:0] xk_V_38;
reg   [13:0] xk_V_39;
reg   [13:0] xk_V_40;
reg   [13:0] xk_V_41;
reg   [13:0] xk_V_42;
reg   [13:0] xk_V_43;
reg   [13:0] xk_V_44;
reg   [13:0] xk_V_45;
reg   [13:0] xk_V_46;
reg   [13:0] xk_V_47;
reg   [13:0] xk_V_48;
reg   [13:0] xk_V_49;
reg   [13:0] xk_V_50;
reg   [13:0] xk_V_51;
reg   [13:0] xk_V_52;
reg   [13:0] xk_V_53;
reg   [13:0] xk_V_54;
reg   [13:0] xk_V_55;
reg   [13:0] xk_V_56;
reg   [13:0] xk_V_57;
reg   [13:0] xk_V_58;
reg   [13:0] xk_V_59;
reg   [13:0] xk_V_60;
reg   [13:0] xk_V_61;
reg   [13:0] xk_V_62;
reg   [15:0] wk_V_8;
reg   [15:0] wk_V_9;
reg   [15:0] wk_V_10;
reg   [15:0] wk_V_11;
reg   [15:0] wk_V_12;
reg   [15:0] wk_V_13;
reg   [15:0] wk_V_14;
reg   [15:0] wk_V_15;
reg   [15:0] wk_V_16;
reg   [15:0] wk_V_17;
reg   [15:0] wk_V_18;
reg   [15:0] wk_V_19;
reg   [15:0] wk_V_20;
reg   [15:0] wk_V_21;
reg   [15:0] wk_V_22;
reg   [15:0] wk_V_23;
reg   [15:0] wk_V_24;
reg   [15:0] wk_V_25;
reg   [15:0] wk_V_26;
reg   [15:0] wk_V_27;
reg   [15:0] wk_V_28;
reg   [15:0] wk_V_29;
reg   [15:0] wk_V_30;
reg   [15:0] wk_V_31;
reg   [15:0] wk_V_32;
reg   [15:0] wk_V_33;
reg   [15:0] wk_V_34;
reg   [15:0] wk_V_35;
reg   [15:0] wk_V_36;
reg   [15:0] wk_V_37;
reg   [15:0] wk_V_38;
reg   [15:0] wk_V_39;
reg   [15:0] wk_V_40;
reg   [15:0] wk_V_41;
reg   [15:0] wk_V_42;
reg   [15:0] wk_V_43;
reg   [15:0] wk_V_44;
reg   [15:0] wk_V_45;
reg   [15:0] wk_V_46;
reg   [15:0] wk_V_47;
reg   [15:0] wk_V_48;
reg   [15:0] wk_V_49;
reg   [15:0] wk_V_50;
reg   [15:0] wk_V_51;
reg   [15:0] wk_V_52;
reg   [15:0] wk_V_53;
reg   [15:0] wk_V_54;
reg   [15:0] wk_V_55;
reg   [15:0] wk_V_56;
reg   [15:0] wk_V_57;
reg   [15:0] wk_V_58;
reg   [15:0] wk_V_59;
reg   [15:0] wk_V_60;
reg   [15:0] wk_V_61;
reg   [15:0] wk_V_62;
reg   [15:0] wk_V_63;
reg   [6:0] i1_reg_607;
reg   [13:0] xk_V_0_load_reg_2425;
wire   [5:0] i_1_fu_1279_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] tmp_fu_1273_p2;
wire    ap_CS_fsm_state3;
reg   [13:0] xk_V_1_load_reg_2478;
reg   [13:0] xk_V_2_load_reg_2484;
reg   [13:0] xk_V_3_load_reg_2490;
reg   [13:0] xk_V_4_load_reg_2496;
reg   [13:0] xk_V_5_load_reg_2502;
reg   [13:0] xk_V_6_load_reg_2508;
reg   [13:0] xk_V_7_load_reg_2514;
wire   [13:0] grp_dotProd_fu_884_ap_return;
reg  signed [13:0] yn_V_reg_2520;
wire    ap_CS_fsm_state4;
wire    grp_dotProd_fu_884_ap_ready;
wire    grp_dotProd_fu_884_ap_done;
wire  signed [31:0] r_V_1_cast_fu_1689_p1;
reg  signed [31:0] r_V_1_cast_reg_2525;
reg   [13:0] xk_V_63_load_reg_2530;
reg   [13:0] xk_V_8_load_1_reg_2535;
reg   [13:0] xk_V_9_load_1_reg_2540;
reg   [13:0] xk_V_10_load_1_reg_2545;
reg   [13:0] xk_V_11_load_1_reg_2550;
reg   [13:0] xk_V_12_load_1_reg_2555;
reg   [13:0] xk_V_13_load_1_reg_2560;
reg   [13:0] xk_V_14_load_1_reg_2565;
reg   [13:0] xk_V_15_load_1_reg_2570;
reg   [13:0] xk_V_16_load_1_reg_2575;
reg   [13:0] xk_V_17_load_1_reg_2580;
reg   [13:0] xk_V_18_load_1_reg_2585;
reg   [13:0] xk_V_19_load_1_reg_2590;
reg   [13:0] xk_V_20_load_1_reg_2595;
reg   [13:0] xk_V_21_load_1_reg_2600;
reg   [13:0] xk_V_22_load_1_reg_2605;
reg   [13:0] xk_V_23_load_1_reg_2610;
reg   [13:0] xk_V_24_load_1_reg_2615;
reg   [13:0] xk_V_25_load_1_reg_2620;
reg   [13:0] xk_V_26_load_1_reg_2625;
reg   [13:0] xk_V_27_load_1_reg_2630;
reg   [13:0] xk_V_28_load_1_reg_2635;
reg   [13:0] xk_V_29_load_1_reg_2640;
reg   [13:0] xk_V_30_load_1_reg_2645;
reg   [13:0] xk_V_31_load_1_reg_2650;
reg   [13:0] xk_V_32_load_1_reg_2655;
reg   [13:0] xk_V_33_load_1_reg_2660;
reg   [13:0] xk_V_34_load_1_reg_2665;
reg   [13:0] xk_V_35_load_1_reg_2670;
reg   [13:0] xk_V_36_load_1_reg_2675;
reg   [13:0] xk_V_37_load_1_reg_2680;
reg   [13:0] xk_V_38_load_1_reg_2685;
reg   [13:0] xk_V_39_load_1_reg_2690;
reg   [13:0] xk_V_40_load_1_reg_2695;
reg   [13:0] xk_V_41_load_1_reg_2700;
reg   [13:0] xk_V_42_load_1_reg_2705;
reg   [13:0] xk_V_43_load_1_reg_2710;
reg   [13:0] xk_V_44_load_1_reg_2715;
reg   [13:0] xk_V_45_load_1_reg_2720;
reg   [13:0] xk_V_46_load_1_reg_2725;
reg   [13:0] xk_V_47_load_1_reg_2730;
reg   [13:0] xk_V_48_load_1_reg_2735;
reg   [13:0] xk_V_49_load_1_reg_2740;
reg   [13:0] xk_V_50_load_1_reg_2745;
reg   [13:0] xk_V_51_load_1_reg_2750;
reg   [13:0] xk_V_52_load_1_reg_2755;
reg   [13:0] xk_V_53_load_1_reg_2760;
reg   [13:0] xk_V_54_load_1_reg_2765;
reg   [13:0] xk_V_55_load_1_reg_2770;
reg   [13:0] xk_V_56_load_1_reg_2775;
reg   [13:0] xk_V_57_load_1_reg_2780;
reg   [13:0] xk_V_58_load_1_reg_2785;
reg   [13:0] xk_V_59_load_1_reg_2790;
reg   [13:0] xk_V_60_load_1_reg_2795;
reg   [13:0] xk_V_61_load_1_reg_2800;
reg   [13:0] xk_V_62_load_1_reg_2805;
wire   [0:0] exitcond_fu_1697_p2;
reg   [0:0] exitcond_reg_2810;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state5_pp1_stage0_iter0;
wire    ap_block_state6_pp1_stage0_iter1;
wire    ap_block_state7_pp1_stage0_iter2;
wire    ap_block_pp1_stage0_11001;
reg   [0:0] exitcond_reg_2810_pp1_iter1_reg;
wire   [6:0] i_2_fu_1703_p2;
reg    ap_enable_reg_pp1_iter0;
wire   [5:0] tmp_2_fu_1709_p1;
reg   [5:0] tmp_2_reg_2819;
reg   [5:0] tmp_2_reg_2819_pp1_iter1_reg;
wire  signed [31:0] r_V_2_fu_2408_p2;
reg  signed [31:0] r_V_2_reg_2823;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state5;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter2;
wire    grp_dotProd_fu_884_ap_start;
wire    grp_dotProd_fu_884_ap_idle;
wire   [5:0] ap_phi_mux_i_phi_fu_469_p4;
reg   [5:0] i_reg_465;
reg   [13:0] ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
wire   [13:0] ap_phi_reg_pp1_iter0_UnifiedRetVal_i_reg_618;
reg  signed [13:0] ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618;
reg   [15:0] ap_phi_mux_p_Val2_1_phi_fu_754_p128;
wire   [15:0] ap_phi_reg_pp1_iter2_p_Val2_1_reg_751;
wire    ap_block_pp1_stage0;
reg    grp_dotProd_fu_884_ap_start_reg;
wire    ap_CS_fsm_state8;
wire  signed [13:0] rhs_V_fu_1671_p0;
wire  signed [14:0] lhs_V_fu_1668_p1;
wire  signed [14:0] rhs_V_fu_1671_p1;
wire   [14:0] ret_V_fu_1675_p2;
wire   [17:0] r_V_fu_1681_p3;
wire  signed [37:0] rhs_V_cast_fu_2005_p1;
wire   [37:0] lhs_V_1_fu_1997_p3;
wire   [37:0] ret_V_2_fu_2008_p2;
wire  signed [17:0] r_V_2_fu_2408_p0;
reg   [5:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_1628;
reg    ap_condition_664;
reg    ap_condition_368;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 xk_V_0 = 14'd0;
#0 wk_V_0 = 16'd0;
#0 wk_V_1 = 16'd0;
#0 wk_V_2 = 16'd0;
#0 wk_V_3 = 16'd0;
#0 wk_V_4 = 16'd0;
#0 wk_V_5 = 16'd0;
#0 wk_V_6 = 16'd0;
#0 wk_V_7 = 16'd0;
#0 xk_V_1 = 14'd0;
#0 xk_V_2 = 14'd0;
#0 xk_V_3 = 14'd0;
#0 xk_V_4 = 14'd0;
#0 xk_V_5 = 14'd0;
#0 xk_V_6 = 14'd0;
#0 xk_V_7 = 14'd0;
#0 xk_V_63 = 14'd0;
#0 xk_V_8 = 14'd0;
#0 xk_V_9 = 14'd0;
#0 xk_V_10 = 14'd0;
#0 xk_V_11 = 14'd0;
#0 xk_V_12 = 14'd0;
#0 xk_V_13 = 14'd0;
#0 xk_V_14 = 14'd0;
#0 xk_V_15 = 14'd0;
#0 xk_V_16 = 14'd0;
#0 xk_V_17 = 14'd0;
#0 xk_V_18 = 14'd0;
#0 xk_V_19 = 14'd0;
#0 xk_V_20 = 14'd0;
#0 xk_V_21 = 14'd0;
#0 xk_V_22 = 14'd0;
#0 xk_V_23 = 14'd0;
#0 xk_V_24 = 14'd0;
#0 xk_V_25 = 14'd0;
#0 xk_V_26 = 14'd0;
#0 xk_V_27 = 14'd0;
#0 xk_V_28 = 14'd0;
#0 xk_V_29 = 14'd0;
#0 xk_V_30 = 14'd0;
#0 xk_V_31 = 14'd0;
#0 xk_V_32 = 14'd0;
#0 xk_V_33 = 14'd0;
#0 xk_V_34 = 14'd0;
#0 xk_V_35 = 14'd0;
#0 xk_V_36 = 14'd0;
#0 xk_V_37 = 14'd0;
#0 xk_V_38 = 14'd0;
#0 xk_V_39 = 14'd0;
#0 xk_V_40 = 14'd0;
#0 xk_V_41 = 14'd0;
#0 xk_V_42 = 14'd0;
#0 xk_V_43 = 14'd0;
#0 xk_V_44 = 14'd0;
#0 xk_V_45 = 14'd0;
#0 xk_V_46 = 14'd0;
#0 xk_V_47 = 14'd0;
#0 xk_V_48 = 14'd0;
#0 xk_V_49 = 14'd0;
#0 xk_V_50 = 14'd0;
#0 xk_V_51 = 14'd0;
#0 xk_V_52 = 14'd0;
#0 xk_V_53 = 14'd0;
#0 xk_V_54 = 14'd0;
#0 xk_V_55 = 14'd0;
#0 xk_V_56 = 14'd0;
#0 xk_V_57 = 14'd0;
#0 xk_V_58 = 14'd0;
#0 xk_V_59 = 14'd0;
#0 xk_V_60 = 14'd0;
#0 xk_V_61 = 14'd0;
#0 xk_V_62 = 14'd0;
#0 wk_V_8 = 16'd0;
#0 wk_V_9 = 16'd0;
#0 wk_V_10 = 16'd0;
#0 wk_V_11 = 16'd0;
#0 wk_V_12 = 16'd0;
#0 wk_V_13 = 16'd0;
#0 wk_V_14 = 16'd0;
#0 wk_V_15 = 16'd0;
#0 wk_V_16 = 16'd0;
#0 wk_V_17 = 16'd0;
#0 wk_V_18 = 16'd0;
#0 wk_V_19 = 16'd0;
#0 wk_V_20 = 16'd0;
#0 wk_V_21 = 16'd0;
#0 wk_V_22 = 16'd0;
#0 wk_V_23 = 16'd0;
#0 wk_V_24 = 16'd0;
#0 wk_V_25 = 16'd0;
#0 wk_V_26 = 16'd0;
#0 wk_V_27 = 16'd0;
#0 wk_V_28 = 16'd0;
#0 wk_V_29 = 16'd0;
#0 wk_V_30 = 16'd0;
#0 wk_V_31 = 16'd0;
#0 wk_V_32 = 16'd0;
#0 wk_V_33 = 16'd0;
#0 wk_V_34 = 16'd0;
#0 wk_V_35 = 16'd0;
#0 wk_V_36 = 16'd0;
#0 wk_V_37 = 16'd0;
#0 wk_V_38 = 16'd0;
#0 wk_V_39 = 16'd0;
#0 wk_V_40 = 16'd0;
#0 wk_V_41 = 16'd0;
#0 wk_V_42 = 16'd0;
#0 wk_V_43 = 16'd0;
#0 wk_V_44 = 16'd0;
#0 wk_V_45 = 16'd0;
#0 wk_V_46 = 16'd0;
#0 wk_V_47 = 16'd0;
#0 wk_V_48 = 16'd0;
#0 wk_V_49 = 16'd0;
#0 wk_V_50 = 16'd0;
#0 wk_V_51 = 16'd0;
#0 wk_V_52 = 16'd0;
#0 wk_V_53 = 16'd0;
#0 wk_V_54 = 16'd0;
#0 wk_V_55 = 16'd0;
#0 wk_V_56 = 16'd0;
#0 wk_V_57 = 16'd0;
#0 wk_V_58 = 16'd0;
#0 wk_V_59 = 16'd0;
#0 wk_V_60 = 16'd0;
#0 wk_V_61 = 16'd0;
#0 wk_V_62 = 16'd0;
#0 wk_V_63 = 16'd0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 grp_dotProd_fu_884_ap_start_reg = 1'b0;
end

dotProd grp_dotProd_fu_884(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dotProd_fu_884_ap_start),
    .ap_done(grp_dotProd_fu_884_ap_done),
    .ap_idle(grp_dotProd_fu_884_ap_idle),
    .ap_ready(grp_dotProd_fu_884_ap_ready),
    .w_0_V_read(wk_V_0),
    .w_1_V_read(wk_V_1),
    .w_2_V_read(wk_V_2),
    .w_3_V_read(wk_V_3),
    .w_4_V_read(wk_V_4),
    .w_5_V_read(wk_V_5),
    .w_6_V_read(wk_V_6),
    .w_7_V_read(wk_V_7),
    .x_0_V_read(xn_V),
    .x_1_V_read(xk_V_1_load_reg_2478),
    .x_2_V_read(xk_V_2_load_reg_2484),
    .x_3_V_read(xk_V_3_load_reg_2490),
    .x_4_V_read(xk_V_4_load_reg_2496),
    .x_5_V_read(xk_V_5_load_reg_2502),
    .x_6_V_read(xk_V_6_load_reg_2508),
    .x_7_V_read(xk_V_7_load_reg_2514),
    .ap_return(grp_dotProd_fu_884_ap_return)
);

lms_mul_mul_18s_1cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 32 ))
lms_mul_mul_18s_1cud_U21(
    .din0(r_V_2_fu_2408_p0),
    .din1(ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618),
    .dout(r_V_2_fu_2408_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((grp_dotProd_fu_884_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state5)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state5);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end else if (((grp_dotProd_fu_884_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp1_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dotProd_fu_884_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dotProd_fu_884_ap_start_reg <= 1'b1;
        end else if ((grp_dotProd_fu_884_ap_ready == 1'b1)) begin
            grp_dotProd_fu_884_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_368)) begin
        if (((tmp_2_fu_1709_p1 == 6'd0) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xn_V;
        end else if (((tmp_2_fu_1709_p1 == 6'd63) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_63_load_reg_2530;
        end else if (((tmp_2_fu_1709_p1 == 6'd62) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_62_load_1_reg_2805;
        end else if (((tmp_2_fu_1709_p1 == 6'd61) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_61_load_1_reg_2800;
        end else if (((tmp_2_fu_1709_p1 == 6'd60) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_60_load_1_reg_2795;
        end else if (((tmp_2_fu_1709_p1 == 6'd59) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_59_load_1_reg_2790;
        end else if (((tmp_2_fu_1709_p1 == 6'd58) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_58_load_1_reg_2785;
        end else if (((tmp_2_fu_1709_p1 == 6'd57) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_57_load_1_reg_2780;
        end else if (((tmp_2_fu_1709_p1 == 6'd56) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_56_load_1_reg_2775;
        end else if (((tmp_2_fu_1709_p1 == 6'd55) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_55_load_1_reg_2770;
        end else if (((tmp_2_fu_1709_p1 == 6'd54) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_54_load_1_reg_2765;
        end else if (((tmp_2_fu_1709_p1 == 6'd53) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_53_load_1_reg_2760;
        end else if (((tmp_2_fu_1709_p1 == 6'd52) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_52_load_1_reg_2755;
        end else if (((tmp_2_fu_1709_p1 == 6'd51) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_51_load_1_reg_2750;
        end else if (((tmp_2_fu_1709_p1 == 6'd50) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_50_load_1_reg_2745;
        end else if (((tmp_2_fu_1709_p1 == 6'd49) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_49_load_1_reg_2740;
        end else if (((tmp_2_fu_1709_p1 == 6'd48) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_48_load_1_reg_2735;
        end else if (((tmp_2_fu_1709_p1 == 6'd47) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_47_load_1_reg_2730;
        end else if (((tmp_2_fu_1709_p1 == 6'd46) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_46_load_1_reg_2725;
        end else if (((tmp_2_fu_1709_p1 == 6'd45) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_45_load_1_reg_2720;
        end else if (((tmp_2_fu_1709_p1 == 6'd44) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_44_load_1_reg_2715;
        end else if (((tmp_2_fu_1709_p1 == 6'd43) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_43_load_1_reg_2710;
        end else if (((tmp_2_fu_1709_p1 == 6'd42) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_42_load_1_reg_2705;
        end else if (((tmp_2_fu_1709_p1 == 6'd41) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_41_load_1_reg_2700;
        end else if (((tmp_2_fu_1709_p1 == 6'd40) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_40_load_1_reg_2695;
        end else if (((tmp_2_fu_1709_p1 == 6'd39) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_39_load_1_reg_2690;
        end else if (((tmp_2_fu_1709_p1 == 6'd38) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_38_load_1_reg_2685;
        end else if (((tmp_2_fu_1709_p1 == 6'd37) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_37_load_1_reg_2680;
        end else if (((tmp_2_fu_1709_p1 == 6'd36) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_36_load_1_reg_2675;
        end else if (((tmp_2_fu_1709_p1 == 6'd35) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_35_load_1_reg_2670;
        end else if (((tmp_2_fu_1709_p1 == 6'd34) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_34_load_1_reg_2665;
        end else if (((tmp_2_fu_1709_p1 == 6'd33) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_33_load_1_reg_2660;
        end else if (((tmp_2_fu_1709_p1 == 6'd32) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_32_load_1_reg_2655;
        end else if (((tmp_2_fu_1709_p1 == 6'd31) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_31_load_1_reg_2650;
        end else if (((tmp_2_fu_1709_p1 == 6'd30) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_30_load_1_reg_2645;
        end else if (((tmp_2_fu_1709_p1 == 6'd29) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_29_load_1_reg_2640;
        end else if (((tmp_2_fu_1709_p1 == 6'd28) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_28_load_1_reg_2635;
        end else if (((tmp_2_fu_1709_p1 == 6'd27) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_27_load_1_reg_2630;
        end else if (((tmp_2_fu_1709_p1 == 6'd26) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_26_load_1_reg_2625;
        end else if (((tmp_2_fu_1709_p1 == 6'd25) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_25_load_1_reg_2620;
        end else if (((tmp_2_fu_1709_p1 == 6'd24) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_24_load_1_reg_2615;
        end else if (((tmp_2_fu_1709_p1 == 6'd23) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_23_load_1_reg_2610;
        end else if (((tmp_2_fu_1709_p1 == 6'd22) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_22_load_1_reg_2605;
        end else if (((tmp_2_fu_1709_p1 == 6'd21) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_21_load_1_reg_2600;
        end else if (((tmp_2_fu_1709_p1 == 6'd20) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_20_load_1_reg_2595;
        end else if (((tmp_2_fu_1709_p1 == 6'd19) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_19_load_1_reg_2590;
        end else if (((tmp_2_fu_1709_p1 == 6'd18) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_18_load_1_reg_2585;
        end else if (((tmp_2_fu_1709_p1 == 6'd17) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_17_load_1_reg_2580;
        end else if (((tmp_2_fu_1709_p1 == 6'd16) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_16_load_1_reg_2575;
        end else if (((tmp_2_fu_1709_p1 == 6'd15) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_15_load_1_reg_2570;
        end else if (((tmp_2_fu_1709_p1 == 6'd14) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_14_load_1_reg_2565;
        end else if (((tmp_2_fu_1709_p1 == 6'd13) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_13_load_1_reg_2560;
        end else if (((tmp_2_fu_1709_p1 == 6'd12) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_12_load_1_reg_2555;
        end else if (((tmp_2_fu_1709_p1 == 6'd11) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_11_load_1_reg_2550;
        end else if (((tmp_2_fu_1709_p1 == 6'd10) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_10_load_1_reg_2545;
        end else if (((tmp_2_fu_1709_p1 == 6'd9) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_9_load_1_reg_2540;
        end else if (((tmp_2_fu_1709_p1 == 6'd8) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_8_load_1_reg_2535;
        end else if (((tmp_2_fu_1709_p1 == 6'd7) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_7_load_reg_2514;
        end else if (((tmp_2_fu_1709_p1 == 6'd6) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_6_load_reg_2508;
        end else if (((tmp_2_fu_1709_p1 == 6'd5) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_5_load_reg_2502;
        end else if (((tmp_2_fu_1709_p1 == 6'd4) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_4_load_reg_2496;
        end else if (((tmp_2_fu_1709_p1 == 6'd3) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_3_load_reg_2490;
        end else if (((tmp_2_fu_1709_p1 == 6'd2) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_2_load_reg_2484;
        end else if (((tmp_2_fu_1709_p1 == 6'd1) & (exitcond_fu_1697_p2 == 1'd0))) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= xk_V_1_load_reg_2478;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp1_iter1_UnifiedRetVal_i_reg_618 <= ap_phi_reg_pp1_iter0_UnifiedRetVal_i_reg_618;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_fu_1697_p2 == 1'd0))) begin
        i1_reg_607 <= i_2_fu_1703_p2;
    end else if (((grp_dotProd_fu_884_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        i1_reg_607 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        i_reg_465 <= i_1_fu_1279_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_reg_465 <= 6'd63;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        exitcond_reg_2810 <= exitcond_fu_1697_p2;
        exitcond_reg_2810_pp1_iter1_reg <= exitcond_reg_2810;
        r_V_2_reg_2823 <= r_V_2_fu_2408_p2;
        tmp_2_reg_2819_pp1_iter1_reg <= tmp_2_reg_2819;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dotProd_fu_884_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        r_V_1_cast_reg_2525[31 : 3] <= r_V_1_cast_fu_1689_p1[31 : 3];
        xk_V_10_load_1_reg_2545 <= xk_V_10;
        xk_V_11_load_1_reg_2550 <= xk_V_11;
        xk_V_12_load_1_reg_2555 <= xk_V_12;
        xk_V_13_load_1_reg_2560 <= xk_V_13;
        xk_V_14_load_1_reg_2565 <= xk_V_14;
        xk_V_15_load_1_reg_2570 <= xk_V_15;
        xk_V_16_load_1_reg_2575 <= xk_V_16;
        xk_V_17_load_1_reg_2580 <= xk_V_17;
        xk_V_18_load_1_reg_2585 <= xk_V_18;
        xk_V_19_load_1_reg_2590 <= xk_V_19;
        xk_V_20_load_1_reg_2595 <= xk_V_20;
        xk_V_21_load_1_reg_2600 <= xk_V_21;
        xk_V_22_load_1_reg_2605 <= xk_V_22;
        xk_V_23_load_1_reg_2610 <= xk_V_23;
        xk_V_24_load_1_reg_2615 <= xk_V_24;
        xk_V_25_load_1_reg_2620 <= xk_V_25;
        xk_V_26_load_1_reg_2625 <= xk_V_26;
        xk_V_27_load_1_reg_2630 <= xk_V_27;
        xk_V_28_load_1_reg_2635 <= xk_V_28;
        xk_V_29_load_1_reg_2640 <= xk_V_29;
        xk_V_30_load_1_reg_2645 <= xk_V_30;
        xk_V_31_load_1_reg_2650 <= xk_V_31;
        xk_V_32_load_1_reg_2655 <= xk_V_32;
        xk_V_33_load_1_reg_2660 <= xk_V_33;
        xk_V_34_load_1_reg_2665 <= xk_V_34;
        xk_V_35_load_1_reg_2670 <= xk_V_35;
        xk_V_36_load_1_reg_2675 <= xk_V_36;
        xk_V_37_load_1_reg_2680 <= xk_V_37;
        xk_V_38_load_1_reg_2685 <= xk_V_38;
        xk_V_39_load_1_reg_2690 <= xk_V_39;
        xk_V_40_load_1_reg_2695 <= xk_V_40;
        xk_V_41_load_1_reg_2700 <= xk_V_41;
        xk_V_42_load_1_reg_2705 <= xk_V_42;
        xk_V_43_load_1_reg_2710 <= xk_V_43;
        xk_V_44_load_1_reg_2715 <= xk_V_44;
        xk_V_45_load_1_reg_2720 <= xk_V_45;
        xk_V_46_load_1_reg_2725 <= xk_V_46;
        xk_V_47_load_1_reg_2730 <= xk_V_47;
        xk_V_48_load_1_reg_2735 <= xk_V_48;
        xk_V_49_load_1_reg_2740 <= xk_V_49;
        xk_V_50_load_1_reg_2745 <= xk_V_50;
        xk_V_51_load_1_reg_2750 <= xk_V_51;
        xk_V_52_load_1_reg_2755 <= xk_V_52;
        xk_V_53_load_1_reg_2760 <= xk_V_53;
        xk_V_54_load_1_reg_2765 <= xk_V_54;
        xk_V_55_load_1_reg_2770 <= xk_V_55;
        xk_V_56_load_1_reg_2775 <= xk_V_56;
        xk_V_57_load_1_reg_2780 <= xk_V_57;
        xk_V_58_load_1_reg_2785 <= xk_V_58;
        xk_V_59_load_1_reg_2790 <= xk_V_59;
        xk_V_60_load_1_reg_2795 <= xk_V_60;
        xk_V_61_load_1_reg_2800 <= xk_V_61;
        xk_V_62_load_1_reg_2805 <= xk_V_62;
        xk_V_63_load_reg_2530 <= xk_V_63;
        xk_V_8_load_1_reg_2535 <= xk_V_8;
        xk_V_9_load_1_reg_2540 <= xk_V_9;
        yn_V_reg_2520 <= grp_dotProd_fu_884_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (exitcond_fu_1697_p2 == 1'd0))) begin
        tmp_2_reg_2819 <= tmp_2_fu_1709_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd0) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_0 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_1 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd10) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_10 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd11) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_11 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd12) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_12 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd13) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_13 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd14) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_14 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd15) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_15 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd16) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_16 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd17) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_17 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd18) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_18 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd19) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_19 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd2) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_2 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd20) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_20 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd21) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_21 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd22) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_22 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd23) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_23 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd24) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_24 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd25) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_25 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd26) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_26 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd27) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_27 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd28) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_28 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd29) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_29 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd3) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_3 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd30) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_30 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd31) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_31 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd32) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_32 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd33) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_33 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd34) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_34 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd35) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_35 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd36) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_36 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd37) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_37 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd38) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_38 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd39) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_39 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd4) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_4 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd40) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_40 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd41) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_41 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd42) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_42 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd43) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_43 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd44) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_44 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd45) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_45 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd46) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_46 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd47) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_47 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd48) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_48 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd49) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_49 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd5) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_5 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd50) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_50 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd51) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_51 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd52) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_52 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd53) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_53 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd54) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_54 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd55) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_55 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd56) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_56 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd57) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_57 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd58) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_58 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd59) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_59 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd6) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_6 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd60) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_60 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd61) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_61 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd62) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_62 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd63) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_63 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd7) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_7 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd8) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_8 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_reg_2819_pp1_iter1_reg == 6'd9) & (1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        wk_V_9 <= {{ret_V_2_fu_2008_p2[37:22]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        xk_V_0 <= xn_V;
        xk_V_1_load_reg_2478 <= xk_V_1;
        xk_V_2_load_reg_2484 <= xk_V_2;
        xk_V_3_load_reg_2490 <= xk_V_3;
        xk_V_4_load_reg_2496 <= xk_V_4;
        xk_V_5_load_reg_2502 <= xk_V_5;
        xk_V_6_load_reg_2508 <= xk_V_6;
        xk_V_7_load_reg_2514 <= xk_V_7;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        xk_V_0_load_reg_2425 <= xk_V_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd1) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_1 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd10) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_10 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd11) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_11 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd12) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_12 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd13) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_13 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd14) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_14 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd15) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_15 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd16) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_16 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd17) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_17 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd18) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_18 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd19) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_19 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd2) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_2 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd20) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_20 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd21) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_21 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd22) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_22 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd23) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_23 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd24) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_24 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd25) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_25 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd26) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_26 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd27) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_27 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd28) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_28 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd29) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_29 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd3) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_3 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd30) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_30 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd31) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_31 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd32) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_32 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd33) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_33 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd34) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_34 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd35) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_35 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd36) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_36 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd37) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_37 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd38) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_38 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd39) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_39 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd4) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_4 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd40) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_40 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd41) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_41 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd42) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_42 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd43) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_43 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd44) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_44 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd45) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_45 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd46) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_46 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd47) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_47 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd48) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_48 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd49) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_49 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd5) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_5 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd50) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_50 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd51) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_51 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd52) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_52 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd53) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_53 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd54) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_54 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd55) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_55 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd56) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_56 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd57) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_57 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd58) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_58 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd59) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_59 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd6) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_6 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd60) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_60 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd61) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_61 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd62) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_62 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (((ap_phi_mux_i_phi_fu_469_p4 == 6'd0) & (tmp_fu_1273_p2 == 1'd0)) | ((ap_phi_mux_i_phi_fu_469_p4 == 6'd63) & (tmp_fu_1273_p2 == 1'd0))))) begin
        xk_V_63 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd7) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_7 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd8) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_8 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd9) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
        xk_V_9 <= ap_phi_mux_xk_V_load_phi_phi_fu_479_p126;
    end
end

always @ (*) begin
    if ((exitcond_fu_1697_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1628)) begin
        if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd63)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_63;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd62)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_62;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd61)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_61;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd60)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_60;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd59)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_59;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd58)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_58;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd57)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_57;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd56)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_56;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd55)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_55;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd54)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_54;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd53)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_53;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd52)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_52;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd51)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_51;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd50)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_50;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd49)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_49;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd48)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_48;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd47)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_47;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd46)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_46;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd45)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_45;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd44)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_44;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd43)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_43;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd42)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_42;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd41)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_41;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd40)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_40;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd39)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_39;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd38)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_38;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd37)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_37;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd36)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_36;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd35)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_35;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd34)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_34;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd33)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_33;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd32)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_32;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd31)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_31;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd30)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_30;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd29)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_29;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd28)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_28;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd27)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_27;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd26)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_26;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd25)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_25;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd24)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_24;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd23)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_23;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd22)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_22;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd21)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_21;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd20)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_20;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd19)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_19;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd18)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_18;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd17)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_17;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd16)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_16;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd15)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_15;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd14)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_14;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd13)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_13;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd12)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_12;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd11)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_11;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd10)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_10;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd9)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_9;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd8)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_8;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd7)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_7;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd6)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_6;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd5)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_5;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd4)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_4;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd3)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_3;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd2)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_2;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd1)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_1;
        end else if ((tmp_2_reg_2819_pp1_iter1_reg == 6'd0)) begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = wk_V_0;
        end else begin
            ap_phi_mux_p_Val2_1_phi_fu_754_p128 = ap_phi_reg_pp1_iter2_p_Val2_1_reg_751;
        end
    end else begin
        ap_phi_mux_p_Val2_1_phi_fu_754_p128 = ap_phi_reg_pp1_iter2_p_Val2_1_reg_751;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd1) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_0_load_reg_2425;
        end else if ((1'b1 == ap_condition_664)) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_62;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd62) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_61;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd61) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_60;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd60) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_59;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd59) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_58;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd58) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_57;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd57) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_56;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd56) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_55;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd55) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_54;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd54) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_53;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd53) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_52;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd52) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_51;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd51) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_50;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd50) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_49;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd49) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_48;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd48) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_47;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd47) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_46;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd46) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_45;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd45) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_44;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd44) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_43;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd43) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_42;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd42) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_41;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd41) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_40;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd40) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_39;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd39) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_38;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd38) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_37;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd37) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_36;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd36) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_35;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd35) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_34;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd34) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_33;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd33) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_32;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd32) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_31;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd31) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_30;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd30) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_29;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd29) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_28;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd28) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_27;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd27) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_26;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd26) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_25;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd25) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_24;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd24) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_23;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd23) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_22;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd22) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_21;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd21) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_20;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd20) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_19;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd19) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_18;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd18) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_17;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd17) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_16;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd16) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_15;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd15) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_14;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd14) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_13;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd13) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_12;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd12) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_11;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd11) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_10;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd10) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_9;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd9) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_8;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd8) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_7;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd7) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_6;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd6) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_5;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd5) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_4;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd4) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_3;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd3) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_2;
        end else if (((ap_phi_mux_i_phi_fu_469_p4 == 6'd2) & (tmp_fu_1273_p2 == 1'd0))) begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = xk_V_1;
        end else begin
            ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = 'bx;
        end
    end else begin
        ap_phi_mux_xk_V_load_phi_phi_fu_479_p126 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        y_V_ap_vld = 1'b1;
    end else begin
        y_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (tmp_fu_1273_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_dotProd_fu_884_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (exitcond_fu_1697_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter2 == 1'b1)) | ((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (exitcond_fu_1697_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd5];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state5_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1628 = ((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (exitcond_reg_2810_pp1_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_condition_368 = ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_condition_664 = (((ap_phi_mux_i_phi_fu_469_p4 == 6'd0) & (tmp_fu_1273_p2 == 1'd0)) | ((ap_phi_mux_i_phi_fu_469_p4 == 6'd63) & (tmp_fu_1273_p2 == 1'd0)));
end

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_phi_mux_i_phi_fu_469_p4 = i_reg_465;

assign ap_phi_reg_pp1_iter0_UnifiedRetVal_i_reg_618 = 'bx;

assign ap_phi_reg_pp1_iter2_p_Val2_1_reg_751 = 'bx;

assign exitcond_fu_1697_p2 = ((i1_reg_607 == 7'd64) ? 1'b1 : 1'b0);

assign grp_dotProd_fu_884_ap_start = grp_dotProd_fu_884_ap_start_reg;

assign i_1_fu_1279_p2 = ($signed(i_reg_465) + $signed(6'd63));

assign i_2_fu_1703_p2 = (i1_reg_607 + 7'd1);

assign lhs_V_1_fu_1997_p3 = {{ap_phi_mux_p_Val2_1_phi_fu_754_p128}, {22'd0}};

assign lhs_V_fu_1668_p1 = $signed(dn_V);

assign r_V_1_cast_fu_1689_p1 = $signed(r_V_fu_1681_p3);

assign r_V_2_fu_2408_p0 = r_V_1_cast_reg_2525;

assign r_V_fu_1681_p3 = {{ret_V_fu_1675_p2}, {3'd0}};

assign ret_V_2_fu_2008_p2 = ($signed(rhs_V_cast_fu_2005_p1) + $signed(lhs_V_1_fu_1997_p3));

assign ret_V_fu_1675_p2 = ($signed(lhs_V_fu_1668_p1) - $signed(rhs_V_fu_1671_p1));

assign rhs_V_cast_fu_2005_p1 = r_V_2_reg_2823;

assign rhs_V_fu_1671_p0 = grp_dotProd_fu_884_ap_return;

assign rhs_V_fu_1671_p1 = rhs_V_fu_1671_p0;

assign tmp_2_fu_1709_p1 = i1_reg_607[5:0];

assign tmp_fu_1273_p2 = ((i_reg_465 == 6'd0) ? 1'b1 : 1'b0);

assign y_V = yn_V_reg_2520;

always @ (posedge ap_clk) begin
    r_V_1_cast_reg_2525[2:0] <= 3'b000;
end

endmodule //lms
