// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "lms.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic lms::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic lms::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> lms::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> lms::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool lms::ap_const_boolean_1 = true;
const bool lms::ap_const_boolean_0 = false;
const sc_lv<32> lms::ap_const_lv32_12 = "10010";
const sc_lv<32> lms::ap_const_lv32_1D = "11101";
const sc_lv<18> lms::ap_const_lv18_0 = "000000000000000000";
const sc_lv<32> lms::ap_const_lv32_1E = "11110";
const sc_lv<32> lms::ap_const_lv32_1F = "11111";
const sc_lv<2> lms::ap_const_lv2_0 = "00";
const sc_lv<3> lms::ap_const_lv3_0 = "000";
const sc_lv<20> lms::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<32> lms::ap_const_lv32_14 = "10100";
const sc_lv<32> lms::ap_const_lv32_23 = "100011";
const sc_lv<1> lms::ap_const_lv1_0 = "0";

lms::lms(sc_module_name name) : sc_module(name), mVcdFile(0) {
    lms_mul_mul_16s_1bkb_U1 = new lms_mul_mul_16s_1bkb<1,1,16,14,30>("lms_mul_mul_16s_1bkb_U1");
    lms_mul_mul_16s_1bkb_U1->din0(wk_V_0);
    lms_mul_mul_16s_1bkb_U1->din1(xn_V);
    lms_mul_mul_16s_1bkb_U1->dout(r_V_5_i_fu_1806_p2);
    lms_mac_muladd_16cud_U2 = new lms_mac_muladd_16cud<1,1,16,14,30,31>("lms_mac_muladd_16cud_U2");
    lms_mac_muladd_16cud_U2->din0(wk_V_1);
    lms_mac_muladd_16cud_U2->din1(xk_V_0);
    lms_mac_muladd_16cud_U2->din2(lhs_V_3_1_i_fu_344_p3);
    lms_mac_muladd_16cud_U2->dout(grp_fu_1813_p3);
    lms_mac_muladd_16dEe_U3 = new lms_mac_muladd_16dEe<1,1,16,14,31,32>("lms_mac_muladd_16dEe_U3");
    lms_mac_muladd_16dEe_U3->din0(wk_V_2);
    lms_mac_muladd_16dEe_U3->din1(xk_V_1);
    lms_mac_muladd_16dEe_U3->din2(tmp_1_fu_373_p3);
    lms_mac_muladd_16dEe_U3->dout(grp_fu_1822_p3);
    lms_mac_muladd_16eOg_U4 = new lms_mac_muladd_16eOg<1,1,16,14,32,32>("lms_mac_muladd_16eOg_U4");
    lms_mac_muladd_16eOg_U4->din0(wk_V_3);
    lms_mac_muladd_16eOg_U4->din1(xk_V_2);
    lms_mac_muladd_16eOg_U4->din2(grp_fu_1831_p2);
    lms_mac_muladd_16eOg_U4->dout(grp_fu_1831_p3);
    lms_mac_muladd_16eOg_U5 = new lms_mac_muladd_16eOg<1,1,16,14,32,32>("lms_mac_muladd_16eOg_U5");
    lms_mac_muladd_16eOg_U5->din0(wk_V_4);
    lms_mac_muladd_16eOg_U5->din1(xk_V_3);
    lms_mac_muladd_16eOg_U5->din2(grp_fu_1840_p2);
    lms_mac_muladd_16eOg_U5->dout(grp_fu_1840_p3);
    lms_mac_muladd_16eOg_U6 = new lms_mac_muladd_16eOg<1,1,16,14,32,32>("lms_mac_muladd_16eOg_U6");
    lms_mac_muladd_16eOg_U6->din0(wk_V_5);
    lms_mac_muladd_16eOg_U6->din1(xk_V_4);
    lms_mac_muladd_16eOg_U6->din2(grp_fu_1849_p2);
    lms_mac_muladd_16eOg_U6->dout(grp_fu_1849_p3);
    lms_mac_muladd_16eOg_U7 = new lms_mac_muladd_16eOg<1,1,16,14,32,32>("lms_mac_muladd_16eOg_U7");
    lms_mac_muladd_16eOg_U7->din0(wk_V_6);
    lms_mac_muladd_16eOg_U7->din1(xk_V_5);
    lms_mac_muladd_16eOg_U7->din2(grp_fu_1858_p2);
    lms_mac_muladd_16eOg_U7->dout(grp_fu_1858_p3);
    lms_mul_mul_16s_1bkb_U8 = new lms_mul_mul_16s_1bkb<1,1,16,14,30>("lms_mul_mul_16s_1bkb_U8");
    lms_mul_mul_16s_1bkb_U8->din0(wk_V_7);
    lms_mul_mul_16s_1bkb_U8->din1(xk_V_6);
    lms_mul_mul_16s_1bkb_U8->dout(r_V_5_7_i_fu_1868_p2);
    lms_mac_muladd_20fYi_U9 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U9");
    lms_mac_muladd_20fYi_U9->din0(grp_fu_1875_p0);
    lms_mac_muladd_20fYi_U9->din1(xn_V);
    lms_mac_muladd_20fYi_U9->din2(grp_fu_1875_p2);
    lms_mac_muladd_20fYi_U9->dout(grp_fu_1875_p3);
    lms_mac_muladd_20fYi_U10 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U10");
    lms_mac_muladd_20fYi_U10->din0(grp_fu_1884_p0);
    lms_mac_muladd_20fYi_U10->din1(xk_V_0);
    lms_mac_muladd_20fYi_U10->din2(grp_fu_1884_p2);
    lms_mac_muladd_20fYi_U10->dout(grp_fu_1884_p3);
    lms_mac_muladd_20fYi_U11 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U11");
    lms_mac_muladd_20fYi_U11->din0(grp_fu_1893_p0);
    lms_mac_muladd_20fYi_U11->din1(xk_V_1);
    lms_mac_muladd_20fYi_U11->din2(grp_fu_1893_p2);
    lms_mac_muladd_20fYi_U11->dout(grp_fu_1893_p3);
    lms_mac_muladd_20fYi_U12 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U12");
    lms_mac_muladd_20fYi_U12->din0(grp_fu_1902_p0);
    lms_mac_muladd_20fYi_U12->din1(xk_V_2);
    lms_mac_muladd_20fYi_U12->din2(grp_fu_1902_p2);
    lms_mac_muladd_20fYi_U12->dout(grp_fu_1902_p3);
    lms_mac_muladd_20fYi_U13 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U13");
    lms_mac_muladd_20fYi_U13->din0(grp_fu_1911_p0);
    lms_mac_muladd_20fYi_U13->din1(xk_V_3);
    lms_mac_muladd_20fYi_U13->din2(grp_fu_1911_p2);
    lms_mac_muladd_20fYi_U13->dout(grp_fu_1911_p3);
    lms_mac_muladd_20fYi_U14 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U14");
    lms_mac_muladd_20fYi_U14->din0(grp_fu_1920_p0);
    lms_mac_muladd_20fYi_U14->din1(xk_V_4);
    lms_mac_muladd_20fYi_U14->din2(grp_fu_1920_p2);
    lms_mac_muladd_20fYi_U14->dout(grp_fu_1920_p3);
    lms_mac_muladd_20fYi_U15 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U15");
    lms_mac_muladd_20fYi_U15->din0(grp_fu_1929_p0);
    lms_mac_muladd_20fYi_U15->din1(xk_V_5);
    lms_mac_muladd_20fYi_U15->din2(grp_fu_1929_p2);
    lms_mac_muladd_20fYi_U15->dout(grp_fu_1929_p3);
    lms_mac_muladd_20fYi_U16 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U16");
    lms_mac_muladd_20fYi_U16->din0(grp_fu_1938_p0);
    lms_mac_muladd_20fYi_U16->din1(xk_V_6);
    lms_mac_muladd_20fYi_U16->din2(grp_fu_1938_p2);
    lms_mac_muladd_20fYi_U16->dout(grp_fu_1938_p3);
    lms_mac_muladd_20fYi_U17 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U17");
    lms_mac_muladd_20fYi_U17->din0(grp_fu_1947_p0);
    lms_mac_muladd_20fYi_U17->din1(xk_V_7);
    lms_mac_muladd_20fYi_U17->din2(grp_fu_1947_p2);
    lms_mac_muladd_20fYi_U17->dout(grp_fu_1947_p3);
    lms_mac_muladd_20fYi_U18 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U18");
    lms_mac_muladd_20fYi_U18->din0(grp_fu_1955_p0);
    lms_mac_muladd_20fYi_U18->din1(xk_V_8);
    lms_mac_muladd_20fYi_U18->din2(grp_fu_1955_p2);
    lms_mac_muladd_20fYi_U18->dout(grp_fu_1955_p3);
    lms_mac_muladd_20fYi_U19 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U19");
    lms_mac_muladd_20fYi_U19->din0(grp_fu_1963_p0);
    lms_mac_muladd_20fYi_U19->din1(xk_V_9);
    lms_mac_muladd_20fYi_U19->din2(grp_fu_1963_p2);
    lms_mac_muladd_20fYi_U19->dout(grp_fu_1963_p3);
    lms_mac_muladd_20fYi_U20 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U20");
    lms_mac_muladd_20fYi_U20->din0(grp_fu_1971_p0);
    lms_mac_muladd_20fYi_U20->din1(xk_V_10);
    lms_mac_muladd_20fYi_U20->din2(grp_fu_1971_p2);
    lms_mac_muladd_20fYi_U20->dout(grp_fu_1971_p3);
    lms_mac_muladd_20fYi_U21 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U21");
    lms_mac_muladd_20fYi_U21->din0(grp_fu_1979_p0);
    lms_mac_muladd_20fYi_U21->din1(xk_V_11);
    lms_mac_muladd_20fYi_U21->din2(grp_fu_1979_p2);
    lms_mac_muladd_20fYi_U21->dout(grp_fu_1979_p3);
    lms_mac_muladd_20fYi_U22 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U22");
    lms_mac_muladd_20fYi_U22->din0(grp_fu_1987_p0);
    lms_mac_muladd_20fYi_U22->din1(xk_V_12);
    lms_mac_muladd_20fYi_U22->din2(grp_fu_1987_p2);
    lms_mac_muladd_20fYi_U22->dout(grp_fu_1987_p3);
    lms_mac_muladd_20fYi_U23 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U23");
    lms_mac_muladd_20fYi_U23->din0(grp_fu_1995_p0);
    lms_mac_muladd_20fYi_U23->din1(xk_V_13);
    lms_mac_muladd_20fYi_U23->din2(grp_fu_1995_p2);
    lms_mac_muladd_20fYi_U23->dout(grp_fu_1995_p3);
    lms_mac_muladd_20fYi_U24 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U24");
    lms_mac_muladd_20fYi_U24->din0(grp_fu_2003_p0);
    lms_mac_muladd_20fYi_U24->din1(xk_V_14);
    lms_mac_muladd_20fYi_U24->din2(grp_fu_2003_p2);
    lms_mac_muladd_20fYi_U24->dout(grp_fu_2003_p3);
    lms_mac_muladd_20fYi_U25 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U25");
    lms_mac_muladd_20fYi_U25->din0(grp_fu_2011_p0);
    lms_mac_muladd_20fYi_U25->din1(xk_V_15);
    lms_mac_muladd_20fYi_U25->din2(grp_fu_2011_p2);
    lms_mac_muladd_20fYi_U25->dout(grp_fu_2011_p3);
    lms_mac_muladd_20fYi_U26 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U26");
    lms_mac_muladd_20fYi_U26->din0(grp_fu_2019_p0);
    lms_mac_muladd_20fYi_U26->din1(xk_V_16);
    lms_mac_muladd_20fYi_U26->din2(grp_fu_2019_p2);
    lms_mac_muladd_20fYi_U26->dout(grp_fu_2019_p3);
    lms_mac_muladd_20fYi_U27 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U27");
    lms_mac_muladd_20fYi_U27->din0(grp_fu_2027_p0);
    lms_mac_muladd_20fYi_U27->din1(xk_V_17);
    lms_mac_muladd_20fYi_U27->din2(grp_fu_2027_p2);
    lms_mac_muladd_20fYi_U27->dout(grp_fu_2027_p3);
    lms_mac_muladd_20fYi_U28 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U28");
    lms_mac_muladd_20fYi_U28->din0(grp_fu_2035_p0);
    lms_mac_muladd_20fYi_U28->din1(xk_V_18);
    lms_mac_muladd_20fYi_U28->din2(grp_fu_2035_p2);
    lms_mac_muladd_20fYi_U28->dout(grp_fu_2035_p3);
    lms_mac_muladd_20fYi_U29 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U29");
    lms_mac_muladd_20fYi_U29->din0(grp_fu_2043_p0);
    lms_mac_muladd_20fYi_U29->din1(xk_V_19);
    lms_mac_muladd_20fYi_U29->din2(grp_fu_2043_p2);
    lms_mac_muladd_20fYi_U29->dout(grp_fu_2043_p3);
    lms_mac_muladd_20fYi_U30 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U30");
    lms_mac_muladd_20fYi_U30->din0(grp_fu_2051_p0);
    lms_mac_muladd_20fYi_U30->din1(xk_V_20);
    lms_mac_muladd_20fYi_U30->din2(grp_fu_2051_p2);
    lms_mac_muladd_20fYi_U30->dout(grp_fu_2051_p3);
    lms_mac_muladd_20fYi_U31 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U31");
    lms_mac_muladd_20fYi_U31->din0(grp_fu_2059_p0);
    lms_mac_muladd_20fYi_U31->din1(xk_V_21);
    lms_mac_muladd_20fYi_U31->din2(grp_fu_2059_p2);
    lms_mac_muladd_20fYi_U31->dout(grp_fu_2059_p3);
    lms_mac_muladd_20fYi_U32 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U32");
    lms_mac_muladd_20fYi_U32->din0(grp_fu_2067_p0);
    lms_mac_muladd_20fYi_U32->din1(xk_V_22);
    lms_mac_muladd_20fYi_U32->din2(grp_fu_2067_p2);
    lms_mac_muladd_20fYi_U32->dout(grp_fu_2067_p3);
    lms_mac_muladd_20fYi_U33 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U33");
    lms_mac_muladd_20fYi_U33->din0(grp_fu_2075_p0);
    lms_mac_muladd_20fYi_U33->din1(xk_V_23);
    lms_mac_muladd_20fYi_U33->din2(grp_fu_2075_p2);
    lms_mac_muladd_20fYi_U33->dout(grp_fu_2075_p3);
    lms_mac_muladd_20fYi_U34 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U34");
    lms_mac_muladd_20fYi_U34->din0(grp_fu_2083_p0);
    lms_mac_muladd_20fYi_U34->din1(xk_V_24);
    lms_mac_muladd_20fYi_U34->din2(grp_fu_2083_p2);
    lms_mac_muladd_20fYi_U34->dout(grp_fu_2083_p3);
    lms_mac_muladd_20fYi_U35 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U35");
    lms_mac_muladd_20fYi_U35->din0(grp_fu_2091_p0);
    lms_mac_muladd_20fYi_U35->din1(xk_V_25);
    lms_mac_muladd_20fYi_U35->din2(grp_fu_2091_p2);
    lms_mac_muladd_20fYi_U35->dout(grp_fu_2091_p3);
    lms_mac_muladd_20fYi_U36 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U36");
    lms_mac_muladd_20fYi_U36->din0(grp_fu_2099_p0);
    lms_mac_muladd_20fYi_U36->din1(xk_V_26);
    lms_mac_muladd_20fYi_U36->din2(grp_fu_2099_p2);
    lms_mac_muladd_20fYi_U36->dout(grp_fu_2099_p3);
    lms_mac_muladd_20fYi_U37 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U37");
    lms_mac_muladd_20fYi_U37->din0(grp_fu_2107_p0);
    lms_mac_muladd_20fYi_U37->din1(xk_V_27);
    lms_mac_muladd_20fYi_U37->din2(grp_fu_2107_p2);
    lms_mac_muladd_20fYi_U37->dout(grp_fu_2107_p3);
    lms_mac_muladd_20fYi_U38 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U38");
    lms_mac_muladd_20fYi_U38->din0(grp_fu_2115_p0);
    lms_mac_muladd_20fYi_U38->din1(xk_V_28);
    lms_mac_muladd_20fYi_U38->din2(grp_fu_2115_p2);
    lms_mac_muladd_20fYi_U38->dout(grp_fu_2115_p3);
    lms_mac_muladd_20fYi_U39 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U39");
    lms_mac_muladd_20fYi_U39->din0(grp_fu_2123_p0);
    lms_mac_muladd_20fYi_U39->din1(xk_V_29);
    lms_mac_muladd_20fYi_U39->din2(grp_fu_2123_p2);
    lms_mac_muladd_20fYi_U39->dout(grp_fu_2123_p3);
    lms_mac_muladd_20fYi_U40 = new lms_mac_muladd_20fYi<1,1,20,14,36,36>("lms_mac_muladd_20fYi_U40");
    lms_mac_muladd_20fYi_U40->din0(grp_fu_2131_p0);
    lms_mac_muladd_20fYi_U40->din1(xk_V_30);
    lms_mac_muladd_20fYi_U40->din2(grp_fu_2131_p2);
    lms_mac_muladd_20fYi_U40->dout(grp_fu_2131_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp0_0to0);
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to0 );

    SC_METHOD(thread_grp_fu_1831_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_2_fu_393_p4 );

    SC_METHOD(thread_grp_fu_1840_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_4_fu_418_p4 );

    SC_METHOD(thread_grp_fu_1849_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_5_fu_443_p4 );

    SC_METHOD(thread_grp_fu_1858_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_9_fu_468_p4 );

    SC_METHOD(thread_grp_fu_1875_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1875_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_fu_576_p1 );

    SC_METHOD(thread_grp_fu_1884_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1884_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_1_fu_603_p1 );

    SC_METHOD(thread_grp_fu_1893_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1893_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_2_fu_630_p1 );

    SC_METHOD(thread_grp_fu_1902_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1902_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_3_fu_657_p1 );

    SC_METHOD(thread_grp_fu_1911_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1911_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_4_fu_684_p1 );

    SC_METHOD(thread_grp_fu_1920_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1920_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_5_fu_711_p1 );

    SC_METHOD(thread_grp_fu_1929_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1929_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_6_fu_738_p1 );

    SC_METHOD(thread_grp_fu_1938_p0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( r_V_1_cast_fu_568_p1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1938_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( lhs_V_2_7_fu_765_p1 );

    SC_METHOD(thread_grp_fu_1947_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1947_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_8 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1955_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1955_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_9 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1963_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1963_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_10 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1971_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1971_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_11 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1979_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1979_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_12 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1987_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1987_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_13 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1995_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_1995_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_14 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2003_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2003_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_15 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2011_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2011_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_16 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2019_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2019_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_17 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2027_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2027_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_18 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2035_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2035_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_19 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2043_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2043_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_20 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2051_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2051_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_21 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2059_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2059_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_22 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2067_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2067_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_23 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2075_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2075_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_24 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2083_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2083_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_25 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2091_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2091_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_26 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2099_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2099_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_27 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2107_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2107_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_28 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2115_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2115_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_29 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2123_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2123_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_30 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2131_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( r_V_1_cast_reg_2154 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_2131_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( wk_V_31 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_1_fu_603_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_2_fu_630_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_3_fu_657_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_3 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_4_fu_684_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_5_fu_711_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_5 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_6_fu_738_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_6 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_7_fu_765_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_7 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_2_fu_576_p1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( wk_V_0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_lhs_V_3_1_i_fu_344_p3);
    sensitive << ( tmp_fu_335_p4 );

    SC_METHOD(thread_lhs_V_3_7_i_fu_502_p3);
    sensitive << ( tmp_10_fu_493_p4 );

    SC_METHOD(thread_lhs_V_fu_528_p1);
    sensitive << ( dn_V );

    SC_METHOD(thread_r_V_1_cast_fu_568_p1);
    sensitive << ( r_V_fu_560_p3 );

    SC_METHOD(thread_r_V_fu_560_p3);
    sensitive << ( ret_V_fu_554_p2 );

    SC_METHOD(thread_ret_V_7_i_cast_fu_1037_p2);
    sensitive << ( tmp_7_fu_1027_p1 );
    sensitive << ( tmp_8_fu_1030_p3 );

    SC_METHOD(thread_ret_V_7_i_fu_522_p2);
    sensitive << ( lhs_V_3_7_i_fu_502_p3 );
    sensitive << ( rhs_V_7_i_cast_fu_510_p1 );

    SC_METHOD(thread_ret_V_fu_554_p2);
    sensitive << ( lhs_V_fu_528_p1 );
    sensitive << ( rhs_V_1_cast_fu_550_p1 );

    SC_METHOD(thread_rhs_V_1_cast_fu_550_p1);
    sensitive << ( rhs_V_fu_542_p3 );

    SC_METHOD(thread_rhs_V_7_i_cast_fu_510_p1);
    sensitive << ( r_V_5_7_i_fu_1868_p2 );

    SC_METHOD(thread_rhs_V_fu_542_p3);
    sensitive << ( tmp_12_fu_532_p4 );

    SC_METHOD(thread_tmp_10_fu_493_p4);
    sensitive << ( grp_fu_1858_p3 );

    SC_METHOD(thread_tmp_12_fu_532_p4);
    sensitive << ( ret_V_7_i_fu_522_p2 );

    SC_METHOD(thread_tmp_13_fu_1787_p4);
    sensitive << ( ret_V_7_i_cast_fu_1037_p2 );

    SC_METHOD(thread_tmp_1_fu_373_p3);
    sensitive << ( tmp_3_fu_356_p4 );

    SC_METHOD(thread_tmp_2_fu_393_p4);
    sensitive << ( grp_fu_1822_p3 );

    SC_METHOD(thread_tmp_3_fu_356_p4);
    sensitive << ( grp_fu_1813_p3 );

    SC_METHOD(thread_tmp_4_fu_418_p4);
    sensitive << ( grp_fu_1831_p3 );

    SC_METHOD(thread_tmp_5_fu_443_p4);
    sensitive << ( grp_fu_1840_p3 );

    SC_METHOD(thread_tmp_7_fu_1027_p1);
    sensitive << ( r_V_5_7_i_reg_2144 );

    SC_METHOD(thread_tmp_8_fu_1030_p3);
    sensitive << ( tmp_11_reg_2149 );

    SC_METHOD(thread_tmp_9_fu_468_p4);
    sensitive << ( grp_fu_1849_p3 );

    SC_METHOD(thread_tmp_fu_335_p4);
    sensitive << ( r_V_5_i_fu_1806_p2 );

    SC_METHOD(thread_y_V);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( tmp_13_fu_1787_p4 );

    SC_METHOD(thread_y_V_ap_vld);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    xk_V_30 = "00000000000000";
    xk_V_29 = "00000000000000";
    xk_V_28 = "00000000000000";
    xk_V_27 = "00000000000000";
    xk_V_26 = "00000000000000";
    xk_V_25 = "00000000000000";
    xk_V_24 = "00000000000000";
    xk_V_23 = "00000000000000";
    xk_V_22 = "00000000000000";
    xk_V_21 = "00000000000000";
    xk_V_20 = "00000000000000";
    xk_V_19 = "00000000000000";
    xk_V_18 = "00000000000000";
    xk_V_17 = "00000000000000";
    xk_V_16 = "00000000000000";
    xk_V_15 = "00000000000000";
    xk_V_14 = "00000000000000";
    xk_V_13 = "00000000000000";
    xk_V_12 = "00000000000000";
    xk_V_11 = "00000000000000";
    xk_V_10 = "00000000000000";
    xk_V_9 = "00000000000000";
    xk_V_8 = "00000000000000";
    xk_V_7 = "00000000000000";
    xk_V_6 = "00000000000000";
    xk_V_5 = "00000000000000";
    xk_V_4 = "00000000000000";
    xk_V_3 = "00000000000000";
    xk_V_2 = "00000000000000";
    xk_V_1 = "00000000000000";
    xk_V_0 = "00000000000000";
    wk_V_0 = "0000000000000000";
    wk_V_1 = "0000000000000000";
    wk_V_2 = "0000000000000000";
    wk_V_3 = "0000000000000000";
    wk_V_4 = "0000000000000000";
    wk_V_5 = "0000000000000000";
    wk_V_6 = "0000000000000000";
    wk_V_7 = "0000000000000000";
    wk_V_8 = "0000000000000000";
    wk_V_9 = "0000000000000000";
    wk_V_10 = "0000000000000000";
    wk_V_11 = "0000000000000000";
    wk_V_12 = "0000000000000000";
    wk_V_13 = "0000000000000000";
    wk_V_14 = "0000000000000000";
    wk_V_15 = "0000000000000000";
    wk_V_16 = "0000000000000000";
    wk_V_17 = "0000000000000000";
    wk_V_18 = "0000000000000000";
    wk_V_19 = "0000000000000000";
    wk_V_20 = "0000000000000000";
    wk_V_21 = "0000000000000000";
    wk_V_22 = "0000000000000000";
    wk_V_23 = "0000000000000000";
    wk_V_24 = "0000000000000000";
    wk_V_25 = "0000000000000000";
    wk_V_26 = "0000000000000000";
    wk_V_27 = "0000000000000000";
    wk_V_28 = "0000000000000000";
    wk_V_29 = "0000000000000000";
    wk_V_30 = "0000000000000000";
    wk_V_31 = "0000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "lms_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, y_V, "(port)y_V");
    sc_trace(mVcdFile, y_V_ap_vld, "(port)y_V_ap_vld");
    sc_trace(mVcdFile, xn_V, "(port)xn_V");
    sc_trace(mVcdFile, dn_V, "(port)dn_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, xk_V_30, "xk_V_30");
    sc_trace(mVcdFile, xk_V_29, "xk_V_29");
    sc_trace(mVcdFile, xk_V_28, "xk_V_28");
    sc_trace(mVcdFile, xk_V_27, "xk_V_27");
    sc_trace(mVcdFile, xk_V_26, "xk_V_26");
    sc_trace(mVcdFile, xk_V_25, "xk_V_25");
    sc_trace(mVcdFile, xk_V_24, "xk_V_24");
    sc_trace(mVcdFile, xk_V_23, "xk_V_23");
    sc_trace(mVcdFile, xk_V_22, "xk_V_22");
    sc_trace(mVcdFile, xk_V_21, "xk_V_21");
    sc_trace(mVcdFile, xk_V_20, "xk_V_20");
    sc_trace(mVcdFile, xk_V_19, "xk_V_19");
    sc_trace(mVcdFile, xk_V_18, "xk_V_18");
    sc_trace(mVcdFile, xk_V_17, "xk_V_17");
    sc_trace(mVcdFile, xk_V_16, "xk_V_16");
    sc_trace(mVcdFile, xk_V_15, "xk_V_15");
    sc_trace(mVcdFile, xk_V_14, "xk_V_14");
    sc_trace(mVcdFile, xk_V_13, "xk_V_13");
    sc_trace(mVcdFile, xk_V_12, "xk_V_12");
    sc_trace(mVcdFile, xk_V_11, "xk_V_11");
    sc_trace(mVcdFile, xk_V_10, "xk_V_10");
    sc_trace(mVcdFile, xk_V_9, "xk_V_9");
    sc_trace(mVcdFile, xk_V_8, "xk_V_8");
    sc_trace(mVcdFile, xk_V_7, "xk_V_7");
    sc_trace(mVcdFile, xk_V_6, "xk_V_6");
    sc_trace(mVcdFile, xk_V_5, "xk_V_5");
    sc_trace(mVcdFile, xk_V_4, "xk_V_4");
    sc_trace(mVcdFile, xk_V_3, "xk_V_3");
    sc_trace(mVcdFile, xk_V_2, "xk_V_2");
    sc_trace(mVcdFile, xk_V_1, "xk_V_1");
    sc_trace(mVcdFile, xk_V_0, "xk_V_0");
    sc_trace(mVcdFile, wk_V_0, "wk_V_0");
    sc_trace(mVcdFile, wk_V_1, "wk_V_1");
    sc_trace(mVcdFile, wk_V_2, "wk_V_2");
    sc_trace(mVcdFile, wk_V_3, "wk_V_3");
    sc_trace(mVcdFile, wk_V_4, "wk_V_4");
    sc_trace(mVcdFile, wk_V_5, "wk_V_5");
    sc_trace(mVcdFile, wk_V_6, "wk_V_6");
    sc_trace(mVcdFile, wk_V_7, "wk_V_7");
    sc_trace(mVcdFile, wk_V_8, "wk_V_8");
    sc_trace(mVcdFile, wk_V_9, "wk_V_9");
    sc_trace(mVcdFile, wk_V_10, "wk_V_10");
    sc_trace(mVcdFile, wk_V_11, "wk_V_11");
    sc_trace(mVcdFile, wk_V_12, "wk_V_12");
    sc_trace(mVcdFile, wk_V_13, "wk_V_13");
    sc_trace(mVcdFile, wk_V_14, "wk_V_14");
    sc_trace(mVcdFile, wk_V_15, "wk_V_15");
    sc_trace(mVcdFile, wk_V_16, "wk_V_16");
    sc_trace(mVcdFile, wk_V_17, "wk_V_17");
    sc_trace(mVcdFile, wk_V_18, "wk_V_18");
    sc_trace(mVcdFile, wk_V_19, "wk_V_19");
    sc_trace(mVcdFile, wk_V_20, "wk_V_20");
    sc_trace(mVcdFile, wk_V_21, "wk_V_21");
    sc_trace(mVcdFile, wk_V_22, "wk_V_22");
    sc_trace(mVcdFile, wk_V_23, "wk_V_23");
    sc_trace(mVcdFile, wk_V_24, "wk_V_24");
    sc_trace(mVcdFile, wk_V_25, "wk_V_25");
    sc_trace(mVcdFile, wk_V_26, "wk_V_26");
    sc_trace(mVcdFile, wk_V_27, "wk_V_27");
    sc_trace(mVcdFile, wk_V_28, "wk_V_28");
    sc_trace(mVcdFile, wk_V_29, "wk_V_29");
    sc_trace(mVcdFile, wk_V_30, "wk_V_30");
    sc_trace(mVcdFile, wk_V_31, "wk_V_31");
    sc_trace(mVcdFile, xk_V_6_load_reg_2139, "xk_V_6_load_reg_2139");
    sc_trace(mVcdFile, r_V_5_7_i_fu_1868_p2, "r_V_5_7_i_fu_1868_p2");
    sc_trace(mVcdFile, r_V_5_7_i_reg_2144, "r_V_5_7_i_reg_2144");
    sc_trace(mVcdFile, tmp_11_reg_2149, "tmp_11_reg_2149");
    sc_trace(mVcdFile, r_V_1_cast_fu_568_p1, "r_V_1_cast_fu_568_p1");
    sc_trace(mVcdFile, r_V_1_cast_reg_2154, "r_V_1_cast_reg_2154");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, r_V_5_i_fu_1806_p2, "r_V_5_i_fu_1806_p2");
    sc_trace(mVcdFile, tmp_fu_335_p4, "tmp_fu_335_p4");
    sc_trace(mVcdFile, lhs_V_3_1_i_fu_344_p3, "lhs_V_3_1_i_fu_344_p3");
    sc_trace(mVcdFile, grp_fu_1813_p3, "grp_fu_1813_p3");
    sc_trace(mVcdFile, tmp_3_fu_356_p4, "tmp_3_fu_356_p4");
    sc_trace(mVcdFile, tmp_1_fu_373_p3, "tmp_1_fu_373_p3");
    sc_trace(mVcdFile, grp_fu_1822_p3, "grp_fu_1822_p3");
    sc_trace(mVcdFile, tmp_2_fu_393_p4, "tmp_2_fu_393_p4");
    sc_trace(mVcdFile, grp_fu_1831_p3, "grp_fu_1831_p3");
    sc_trace(mVcdFile, tmp_4_fu_418_p4, "tmp_4_fu_418_p4");
    sc_trace(mVcdFile, grp_fu_1840_p3, "grp_fu_1840_p3");
    sc_trace(mVcdFile, tmp_5_fu_443_p4, "tmp_5_fu_443_p4");
    sc_trace(mVcdFile, grp_fu_1849_p3, "grp_fu_1849_p3");
    sc_trace(mVcdFile, tmp_9_fu_468_p4, "tmp_9_fu_468_p4");
    sc_trace(mVcdFile, grp_fu_1858_p3, "grp_fu_1858_p3");
    sc_trace(mVcdFile, tmp_10_fu_493_p4, "tmp_10_fu_493_p4");
    sc_trace(mVcdFile, lhs_V_3_7_i_fu_502_p3, "lhs_V_3_7_i_fu_502_p3");
    sc_trace(mVcdFile, rhs_V_7_i_cast_fu_510_p1, "rhs_V_7_i_cast_fu_510_p1");
    sc_trace(mVcdFile, ret_V_7_i_fu_522_p2, "ret_V_7_i_fu_522_p2");
    sc_trace(mVcdFile, tmp_12_fu_532_p4, "tmp_12_fu_532_p4");
    sc_trace(mVcdFile, rhs_V_fu_542_p3, "rhs_V_fu_542_p3");
    sc_trace(mVcdFile, lhs_V_fu_528_p1, "lhs_V_fu_528_p1");
    sc_trace(mVcdFile, rhs_V_1_cast_fu_550_p1, "rhs_V_1_cast_fu_550_p1");
    sc_trace(mVcdFile, ret_V_fu_554_p2, "ret_V_fu_554_p2");
    sc_trace(mVcdFile, r_V_fu_560_p3, "r_V_fu_560_p3");
    sc_trace(mVcdFile, lhs_V_2_fu_576_p1, "lhs_V_2_fu_576_p1");
    sc_trace(mVcdFile, grp_fu_1875_p3, "grp_fu_1875_p3");
    sc_trace(mVcdFile, lhs_V_2_1_fu_603_p1, "lhs_V_2_1_fu_603_p1");
    sc_trace(mVcdFile, grp_fu_1884_p3, "grp_fu_1884_p3");
    sc_trace(mVcdFile, lhs_V_2_2_fu_630_p1, "lhs_V_2_2_fu_630_p1");
    sc_trace(mVcdFile, grp_fu_1893_p3, "grp_fu_1893_p3");
    sc_trace(mVcdFile, lhs_V_2_3_fu_657_p1, "lhs_V_2_3_fu_657_p1");
    sc_trace(mVcdFile, grp_fu_1902_p3, "grp_fu_1902_p3");
    sc_trace(mVcdFile, lhs_V_2_4_fu_684_p1, "lhs_V_2_4_fu_684_p1");
    sc_trace(mVcdFile, grp_fu_1911_p3, "grp_fu_1911_p3");
    sc_trace(mVcdFile, lhs_V_2_5_fu_711_p1, "lhs_V_2_5_fu_711_p1");
    sc_trace(mVcdFile, grp_fu_1920_p3, "grp_fu_1920_p3");
    sc_trace(mVcdFile, lhs_V_2_6_fu_738_p1, "lhs_V_2_6_fu_738_p1");
    sc_trace(mVcdFile, grp_fu_1929_p3, "grp_fu_1929_p3");
    sc_trace(mVcdFile, lhs_V_2_7_fu_765_p1, "lhs_V_2_7_fu_765_p1");
    sc_trace(mVcdFile, grp_fu_1938_p3, "grp_fu_1938_p3");
    sc_trace(mVcdFile, tmp_7_fu_1027_p1, "tmp_7_fu_1027_p1");
    sc_trace(mVcdFile, tmp_8_fu_1030_p3, "tmp_8_fu_1030_p3");
    sc_trace(mVcdFile, grp_fu_1947_p3, "grp_fu_1947_p3");
    sc_trace(mVcdFile, grp_fu_1955_p3, "grp_fu_1955_p3");
    sc_trace(mVcdFile, grp_fu_1963_p3, "grp_fu_1963_p3");
    sc_trace(mVcdFile, grp_fu_1971_p3, "grp_fu_1971_p3");
    sc_trace(mVcdFile, grp_fu_1979_p3, "grp_fu_1979_p3");
    sc_trace(mVcdFile, grp_fu_1987_p3, "grp_fu_1987_p3");
    sc_trace(mVcdFile, grp_fu_1995_p3, "grp_fu_1995_p3");
    sc_trace(mVcdFile, grp_fu_2003_p3, "grp_fu_2003_p3");
    sc_trace(mVcdFile, grp_fu_2011_p3, "grp_fu_2011_p3");
    sc_trace(mVcdFile, grp_fu_2019_p3, "grp_fu_2019_p3");
    sc_trace(mVcdFile, grp_fu_2027_p3, "grp_fu_2027_p3");
    sc_trace(mVcdFile, grp_fu_2035_p3, "grp_fu_2035_p3");
    sc_trace(mVcdFile, grp_fu_2043_p3, "grp_fu_2043_p3");
    sc_trace(mVcdFile, grp_fu_2051_p3, "grp_fu_2051_p3");
    sc_trace(mVcdFile, grp_fu_2059_p3, "grp_fu_2059_p3");
    sc_trace(mVcdFile, grp_fu_2067_p3, "grp_fu_2067_p3");
    sc_trace(mVcdFile, grp_fu_2075_p3, "grp_fu_2075_p3");
    sc_trace(mVcdFile, grp_fu_2083_p3, "grp_fu_2083_p3");
    sc_trace(mVcdFile, grp_fu_2091_p3, "grp_fu_2091_p3");
    sc_trace(mVcdFile, grp_fu_2099_p3, "grp_fu_2099_p3");
    sc_trace(mVcdFile, grp_fu_2107_p3, "grp_fu_2107_p3");
    sc_trace(mVcdFile, grp_fu_2115_p3, "grp_fu_2115_p3");
    sc_trace(mVcdFile, grp_fu_2123_p3, "grp_fu_2123_p3");
    sc_trace(mVcdFile, grp_fu_2131_p3, "grp_fu_2131_p3");
    sc_trace(mVcdFile, ret_V_7_i_cast_fu_1037_p2, "ret_V_7_i_cast_fu_1037_p2");
    sc_trace(mVcdFile, tmp_13_fu_1787_p4, "tmp_13_fu_1787_p4");
    sc_trace(mVcdFile, grp_fu_1831_p2, "grp_fu_1831_p2");
    sc_trace(mVcdFile, grp_fu_1840_p2, "grp_fu_1840_p2");
    sc_trace(mVcdFile, grp_fu_1849_p2, "grp_fu_1849_p2");
    sc_trace(mVcdFile, grp_fu_1858_p2, "grp_fu_1858_p2");
    sc_trace(mVcdFile, grp_fu_1875_p0, "grp_fu_1875_p0");
    sc_trace(mVcdFile, grp_fu_1875_p2, "grp_fu_1875_p2");
    sc_trace(mVcdFile, grp_fu_1884_p0, "grp_fu_1884_p0");
    sc_trace(mVcdFile, grp_fu_1884_p2, "grp_fu_1884_p2");
    sc_trace(mVcdFile, grp_fu_1893_p0, "grp_fu_1893_p0");
    sc_trace(mVcdFile, grp_fu_1893_p2, "grp_fu_1893_p2");
    sc_trace(mVcdFile, grp_fu_1902_p0, "grp_fu_1902_p0");
    sc_trace(mVcdFile, grp_fu_1902_p2, "grp_fu_1902_p2");
    sc_trace(mVcdFile, grp_fu_1911_p0, "grp_fu_1911_p0");
    sc_trace(mVcdFile, grp_fu_1911_p2, "grp_fu_1911_p2");
    sc_trace(mVcdFile, grp_fu_1920_p0, "grp_fu_1920_p0");
    sc_trace(mVcdFile, grp_fu_1920_p2, "grp_fu_1920_p2");
    sc_trace(mVcdFile, grp_fu_1929_p0, "grp_fu_1929_p0");
    sc_trace(mVcdFile, grp_fu_1929_p2, "grp_fu_1929_p2");
    sc_trace(mVcdFile, grp_fu_1938_p0, "grp_fu_1938_p0");
    sc_trace(mVcdFile, grp_fu_1938_p2, "grp_fu_1938_p2");
    sc_trace(mVcdFile, grp_fu_1947_p0, "grp_fu_1947_p0");
    sc_trace(mVcdFile, grp_fu_1947_p2, "grp_fu_1947_p2");
    sc_trace(mVcdFile, grp_fu_1955_p0, "grp_fu_1955_p0");
    sc_trace(mVcdFile, grp_fu_1955_p2, "grp_fu_1955_p2");
    sc_trace(mVcdFile, grp_fu_1963_p0, "grp_fu_1963_p0");
    sc_trace(mVcdFile, grp_fu_1963_p2, "grp_fu_1963_p2");
    sc_trace(mVcdFile, grp_fu_1971_p0, "grp_fu_1971_p0");
    sc_trace(mVcdFile, grp_fu_1971_p2, "grp_fu_1971_p2");
    sc_trace(mVcdFile, grp_fu_1979_p0, "grp_fu_1979_p0");
    sc_trace(mVcdFile, grp_fu_1979_p2, "grp_fu_1979_p2");
    sc_trace(mVcdFile, grp_fu_1987_p0, "grp_fu_1987_p0");
    sc_trace(mVcdFile, grp_fu_1987_p2, "grp_fu_1987_p2");
    sc_trace(mVcdFile, grp_fu_1995_p0, "grp_fu_1995_p0");
    sc_trace(mVcdFile, grp_fu_1995_p2, "grp_fu_1995_p2");
    sc_trace(mVcdFile, grp_fu_2003_p0, "grp_fu_2003_p0");
    sc_trace(mVcdFile, grp_fu_2003_p2, "grp_fu_2003_p2");
    sc_trace(mVcdFile, grp_fu_2011_p0, "grp_fu_2011_p0");
    sc_trace(mVcdFile, grp_fu_2011_p2, "grp_fu_2011_p2");
    sc_trace(mVcdFile, grp_fu_2019_p0, "grp_fu_2019_p0");
    sc_trace(mVcdFile, grp_fu_2019_p2, "grp_fu_2019_p2");
    sc_trace(mVcdFile, grp_fu_2027_p0, "grp_fu_2027_p0");
    sc_trace(mVcdFile, grp_fu_2027_p2, "grp_fu_2027_p2");
    sc_trace(mVcdFile, grp_fu_2035_p0, "grp_fu_2035_p0");
    sc_trace(mVcdFile, grp_fu_2035_p2, "grp_fu_2035_p2");
    sc_trace(mVcdFile, grp_fu_2043_p0, "grp_fu_2043_p0");
    sc_trace(mVcdFile, grp_fu_2043_p2, "grp_fu_2043_p2");
    sc_trace(mVcdFile, grp_fu_2051_p0, "grp_fu_2051_p0");
    sc_trace(mVcdFile, grp_fu_2051_p2, "grp_fu_2051_p2");
    sc_trace(mVcdFile, grp_fu_2059_p0, "grp_fu_2059_p0");
    sc_trace(mVcdFile, grp_fu_2059_p2, "grp_fu_2059_p2");
    sc_trace(mVcdFile, grp_fu_2067_p0, "grp_fu_2067_p0");
    sc_trace(mVcdFile, grp_fu_2067_p2, "grp_fu_2067_p2");
    sc_trace(mVcdFile, grp_fu_2075_p0, "grp_fu_2075_p0");
    sc_trace(mVcdFile, grp_fu_2075_p2, "grp_fu_2075_p2");
    sc_trace(mVcdFile, grp_fu_2083_p0, "grp_fu_2083_p0");
    sc_trace(mVcdFile, grp_fu_2083_p2, "grp_fu_2083_p2");
    sc_trace(mVcdFile, grp_fu_2091_p0, "grp_fu_2091_p0");
    sc_trace(mVcdFile, grp_fu_2091_p2, "grp_fu_2091_p2");
    sc_trace(mVcdFile, grp_fu_2099_p0, "grp_fu_2099_p0");
    sc_trace(mVcdFile, grp_fu_2099_p2, "grp_fu_2099_p2");
    sc_trace(mVcdFile, grp_fu_2107_p0, "grp_fu_2107_p0");
    sc_trace(mVcdFile, grp_fu_2107_p2, "grp_fu_2107_p2");
    sc_trace(mVcdFile, grp_fu_2115_p0, "grp_fu_2115_p0");
    sc_trace(mVcdFile, grp_fu_2115_p2, "grp_fu_2115_p2");
    sc_trace(mVcdFile, grp_fu_2123_p0, "grp_fu_2123_p0");
    sc_trace(mVcdFile, grp_fu_2123_p2, "grp_fu_2123_p2");
    sc_trace(mVcdFile, grp_fu_2131_p0, "grp_fu_2131_p0");
    sc_trace(mVcdFile, grp_fu_2131_p2, "grp_fu_2131_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to0, "ap_idle_pp0_0to0");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
    mHdltvinHandle.open("lms.hdltvin.dat");
    mHdltvoutHandle.open("lms.hdltvout.dat");
}

lms::~lms() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete lms_mul_mul_16s_1bkb_U1;
    delete lms_mac_muladd_16cud_U2;
    delete lms_mac_muladd_16dEe_U3;
    delete lms_mac_muladd_16eOg_U4;
    delete lms_mac_muladd_16eOg_U5;
    delete lms_mac_muladd_16eOg_U6;
    delete lms_mac_muladd_16eOg_U7;
    delete lms_mul_mul_16s_1bkb_U8;
    delete lms_mac_muladd_20fYi_U9;
    delete lms_mac_muladd_20fYi_U10;
    delete lms_mac_muladd_20fYi_U11;
    delete lms_mac_muladd_20fYi_U12;
    delete lms_mac_muladd_20fYi_U13;
    delete lms_mac_muladd_20fYi_U14;
    delete lms_mac_muladd_20fYi_U15;
    delete lms_mac_muladd_20fYi_U16;
    delete lms_mac_muladd_20fYi_U17;
    delete lms_mac_muladd_20fYi_U18;
    delete lms_mac_muladd_20fYi_U19;
    delete lms_mac_muladd_20fYi_U20;
    delete lms_mac_muladd_20fYi_U21;
    delete lms_mac_muladd_20fYi_U22;
    delete lms_mac_muladd_20fYi_U23;
    delete lms_mac_muladd_20fYi_U24;
    delete lms_mac_muladd_20fYi_U25;
    delete lms_mac_muladd_20fYi_U26;
    delete lms_mac_muladd_20fYi_U27;
    delete lms_mac_muladd_20fYi_U28;
    delete lms_mac_muladd_20fYi_U29;
    delete lms_mac_muladd_20fYi_U30;
    delete lms_mac_muladd_20fYi_U31;
    delete lms_mac_muladd_20fYi_U32;
    delete lms_mac_muladd_20fYi_U33;
    delete lms_mac_muladd_20fYi_U34;
    delete lms_mac_muladd_20fYi_U35;
    delete lms_mac_muladd_20fYi_U36;
    delete lms_mac_muladd_20fYi_U37;
    delete lms_mac_muladd_20fYi_U38;
    delete lms_mac_muladd_20fYi_U39;
    delete lms_mac_muladd_20fYi_U40;
}

void lms::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        r_V_1_cast_reg_2154 = r_V_1_cast_fu_568_p1.read();
        r_V_5_7_i_reg_2144 = r_V_5_7_i_fu_1868_p2.read();
        tmp_11_reg_2149 = grp_fu_1858_p3.read().range(30, 18);
        xk_V_6_load_reg_2139 = xk_V_6.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        wk_V_0 = grp_fu_1875_p3.read().range(35, 20);
        wk_V_1 = grp_fu_1884_p3.read().range(35, 20);
        wk_V_2 = grp_fu_1893_p3.read().range(35, 20);
        wk_V_3 = grp_fu_1902_p3.read().range(35, 20);
        wk_V_4 = grp_fu_1911_p3.read().range(35, 20);
        wk_V_5 = grp_fu_1920_p3.read().range(35, 20);
        wk_V_6 = grp_fu_1929_p3.read().range(35, 20);
        wk_V_7 = grp_fu_1938_p3.read().range(35, 20);
        xk_V_0 = xn_V.read();
        xk_V_1 = xk_V_0.read();
        xk_V_2 = xk_V_1.read();
        xk_V_3 = xk_V_2.read();
        xk_V_4 = xk_V_3.read();
        xk_V_5 = xk_V_4.read();
        xk_V_6 = xk_V_5.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        wk_V_10 = grp_fu_1963_p3.read().range(35, 20);
        wk_V_11 = grp_fu_1971_p3.read().range(35, 20);
        wk_V_12 = grp_fu_1979_p3.read().range(35, 20);
        wk_V_13 = grp_fu_1987_p3.read().range(35, 20);
        wk_V_14 = grp_fu_1995_p3.read().range(35, 20);
        wk_V_15 = grp_fu_2003_p3.read().range(35, 20);
        wk_V_16 = grp_fu_2011_p3.read().range(35, 20);
        wk_V_17 = grp_fu_2019_p3.read().range(35, 20);
        wk_V_18 = grp_fu_2027_p3.read().range(35, 20);
        wk_V_19 = grp_fu_2035_p3.read().range(35, 20);
        wk_V_20 = grp_fu_2043_p3.read().range(35, 20);
        wk_V_21 = grp_fu_2051_p3.read().range(35, 20);
        wk_V_22 = grp_fu_2059_p3.read().range(35, 20);
        wk_V_23 = grp_fu_2067_p3.read().range(35, 20);
        wk_V_24 = grp_fu_2075_p3.read().range(35, 20);
        wk_V_25 = grp_fu_2083_p3.read().range(35, 20);
        wk_V_26 = grp_fu_2091_p3.read().range(35, 20);
        wk_V_27 = grp_fu_2099_p3.read().range(35, 20);
        wk_V_28 = grp_fu_2107_p3.read().range(35, 20);
        wk_V_29 = grp_fu_2115_p3.read().range(35, 20);
        wk_V_30 = grp_fu_2123_p3.read().range(35, 20);
        wk_V_31 = grp_fu_2131_p3.read().range(35, 20);
        wk_V_8 = grp_fu_1947_p3.read().range(35, 20);
        wk_V_9 = grp_fu_1955_p3.read().range(35, 20);
        xk_V_10 = xk_V_9.read();
        xk_V_11 = xk_V_10.read();
        xk_V_12 = xk_V_11.read();
        xk_V_13 = xk_V_12.read();
        xk_V_14 = xk_V_13.read();
        xk_V_15 = xk_V_14.read();
        xk_V_16 = xk_V_15.read();
        xk_V_17 = xk_V_16.read();
        xk_V_18 = xk_V_17.read();
        xk_V_19 = xk_V_18.read();
        xk_V_20 = xk_V_19.read();
        xk_V_21 = xk_V_20.read();
        xk_V_22 = xk_V_21.read();
        xk_V_23 = xk_V_22.read();
        xk_V_24 = xk_V_23.read();
        xk_V_25 = xk_V_24.read();
        xk_V_26 = xk_V_25.read();
        xk_V_27 = xk_V_26.read();
        xk_V_28 = xk_V_27.read();
        xk_V_29 = xk_V_28.read();
        xk_V_30 = xk_V_29.read();
        xk_V_7 = xk_V_6_load_reg_2139.read();
        xk_V_8 = xk_V_7.read();
        xk_V_9 = xk_V_8.read();
    }
}

void lms::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void lms::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void lms::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void lms::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void lms::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()));
}

void lms::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read());
}

void lms::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void lms::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void lms::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void lms::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void lms::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void lms::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void lms::thread_ap_idle_pp0_0to0() {
    if (esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read())) {
        ap_idle_pp0_0to0 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to0 = ap_const_logic_0;
    }
}

void lms::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void lms::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to0.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void lms::thread_grp_fu_1831_p2() {
    grp_fu_1831_p2 = esl_concat<14,18>(tmp_2_fu_393_p4.read(), ap_const_lv18_0);
}

void lms::thread_grp_fu_1840_p2() {
    grp_fu_1840_p2 = esl_concat<14,18>(tmp_4_fu_418_p4.read(), ap_const_lv18_0);
}

void lms::thread_grp_fu_1849_p2() {
    grp_fu_1849_p2 = esl_concat<14,18>(tmp_5_fu_443_p4.read(), ap_const_lv18_0);
}

void lms::thread_grp_fu_1858_p2() {
    grp_fu_1858_p2 = esl_concat<14,18>(tmp_9_fu_468_p4.read(), ap_const_lv18_0);
}

void lms::thread_grp_fu_1875_p0() {
    grp_fu_1875_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1875_p2() {
    grp_fu_1875_p2 = esl_concat<16,20>(lhs_V_2_fu_576_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1884_p0() {
    grp_fu_1884_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1884_p2() {
    grp_fu_1884_p2 = esl_concat<16,20>(lhs_V_2_1_fu_603_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1893_p0() {
    grp_fu_1893_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1893_p2() {
    grp_fu_1893_p2 = esl_concat<16,20>(lhs_V_2_2_fu_630_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1902_p0() {
    grp_fu_1902_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1902_p2() {
    grp_fu_1902_p2 = esl_concat<16,20>(lhs_V_2_3_fu_657_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1911_p0() {
    grp_fu_1911_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1911_p2() {
    grp_fu_1911_p2 = esl_concat<16,20>(lhs_V_2_4_fu_684_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1920_p0() {
    grp_fu_1920_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1920_p2() {
    grp_fu_1920_p2 = esl_concat<16,20>(lhs_V_2_5_fu_711_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1929_p0() {
    grp_fu_1929_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1929_p2() {
    grp_fu_1929_p2 = esl_concat<16,20>(lhs_V_2_6_fu_738_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1938_p0() {
    grp_fu_1938_p0 =  (sc_lv<20>) (r_V_1_cast_fu_568_p1.read());
}

void lms::thread_grp_fu_1938_p2() {
    grp_fu_1938_p2 = esl_concat<16,20>(lhs_V_2_7_fu_765_p1.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1947_p0() {
    grp_fu_1947_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1947_p2() {
    grp_fu_1947_p2 = esl_concat<16,20>(wk_V_8.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1955_p0() {
    grp_fu_1955_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1955_p2() {
    grp_fu_1955_p2 = esl_concat<16,20>(wk_V_9.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1963_p0() {
    grp_fu_1963_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1963_p2() {
    grp_fu_1963_p2 = esl_concat<16,20>(wk_V_10.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1971_p0() {
    grp_fu_1971_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1971_p2() {
    grp_fu_1971_p2 = esl_concat<16,20>(wk_V_11.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1979_p0() {
    grp_fu_1979_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1979_p2() {
    grp_fu_1979_p2 = esl_concat<16,20>(wk_V_12.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1987_p0() {
    grp_fu_1987_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1987_p2() {
    grp_fu_1987_p2 = esl_concat<16,20>(wk_V_13.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_1995_p0() {
    grp_fu_1995_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_1995_p2() {
    grp_fu_1995_p2 = esl_concat<16,20>(wk_V_14.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2003_p0() {
    grp_fu_2003_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2003_p2() {
    grp_fu_2003_p2 = esl_concat<16,20>(wk_V_15.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2011_p0() {
    grp_fu_2011_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2011_p2() {
    grp_fu_2011_p2 = esl_concat<16,20>(wk_V_16.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2019_p0() {
    grp_fu_2019_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2019_p2() {
    grp_fu_2019_p2 = esl_concat<16,20>(wk_V_17.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2027_p0() {
    grp_fu_2027_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2027_p2() {
    grp_fu_2027_p2 = esl_concat<16,20>(wk_V_18.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2035_p0() {
    grp_fu_2035_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2035_p2() {
    grp_fu_2035_p2 = esl_concat<16,20>(wk_V_19.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2043_p0() {
    grp_fu_2043_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2043_p2() {
    grp_fu_2043_p2 = esl_concat<16,20>(wk_V_20.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2051_p0() {
    grp_fu_2051_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2051_p2() {
    grp_fu_2051_p2 = esl_concat<16,20>(wk_V_21.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2059_p0() {
    grp_fu_2059_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2059_p2() {
    grp_fu_2059_p2 = esl_concat<16,20>(wk_V_22.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2067_p0() {
    grp_fu_2067_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2067_p2() {
    grp_fu_2067_p2 = esl_concat<16,20>(wk_V_23.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2075_p0() {
    grp_fu_2075_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2075_p2() {
    grp_fu_2075_p2 = esl_concat<16,20>(wk_V_24.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2083_p0() {
    grp_fu_2083_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2083_p2() {
    grp_fu_2083_p2 = esl_concat<16,20>(wk_V_25.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2091_p0() {
    grp_fu_2091_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2091_p2() {
    grp_fu_2091_p2 = esl_concat<16,20>(wk_V_26.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2099_p0() {
    grp_fu_2099_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2099_p2() {
    grp_fu_2099_p2 = esl_concat<16,20>(wk_V_27.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2107_p0() {
    grp_fu_2107_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2107_p2() {
    grp_fu_2107_p2 = esl_concat<16,20>(wk_V_28.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2115_p0() {
    grp_fu_2115_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2115_p2() {
    grp_fu_2115_p2 = esl_concat<16,20>(wk_V_29.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2123_p0() {
    grp_fu_2123_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2123_p2() {
    grp_fu_2123_p2 = esl_concat<16,20>(wk_V_30.read(), ap_const_lv20_0);
}

void lms::thread_grp_fu_2131_p0() {
    grp_fu_2131_p0 =  (sc_lv<20>) (r_V_1_cast_reg_2154.read());
}

void lms::thread_grp_fu_2131_p2() {
    grp_fu_2131_p2 = esl_concat<16,20>(wk_V_31.read(), ap_const_lv20_0);
}

void lms::thread_lhs_V_2_1_fu_603_p1() {
    lhs_V_2_1_fu_603_p1 = wk_V_1.read();
}

void lms::thread_lhs_V_2_2_fu_630_p1() {
    lhs_V_2_2_fu_630_p1 = wk_V_2.read();
}

void lms::thread_lhs_V_2_3_fu_657_p1() {
    lhs_V_2_3_fu_657_p1 = wk_V_3.read();
}

void lms::thread_lhs_V_2_4_fu_684_p1() {
    lhs_V_2_4_fu_684_p1 = wk_V_4.read();
}

void lms::thread_lhs_V_2_5_fu_711_p1() {
    lhs_V_2_5_fu_711_p1 = wk_V_5.read();
}

void lms::thread_lhs_V_2_6_fu_738_p1() {
    lhs_V_2_6_fu_738_p1 = wk_V_6.read();
}

void lms::thread_lhs_V_2_7_fu_765_p1() {
    lhs_V_2_7_fu_765_p1 = wk_V_7.read();
}

void lms::thread_lhs_V_2_fu_576_p1() {
    lhs_V_2_fu_576_p1 = wk_V_0.read();
}

void lms::thread_lhs_V_3_1_i_fu_344_p3() {
    lhs_V_3_1_i_fu_344_p3 = esl_concat<12,18>(tmp_fu_335_p4.read(), ap_const_lv18_0);
}

void lms::thread_lhs_V_3_7_i_fu_502_p3() {
    lhs_V_3_7_i_fu_502_p3 = esl_concat<14,18>(tmp_10_fu_493_p4.read(), ap_const_lv18_0);
}

void lms::thread_lhs_V_fu_528_p1() {
    lhs_V_fu_528_p1 = esl_sext<17,14>(dn_V.read());
}

void lms::thread_r_V_1_cast_fu_568_p1() {
    r_V_1_cast_fu_568_p1 = esl_sext<34,20>(r_V_fu_560_p3.read());
}

void lms::thread_r_V_fu_560_p3() {
    r_V_fu_560_p3 = esl_concat<17,3>(ret_V_fu_554_p2.read(), ap_const_lv3_0);
}

void lms::thread_ret_V_7_i_cast_fu_1037_p2() {
    ret_V_7_i_cast_fu_1037_p2 = (!tmp_7_fu_1027_p1.read().is_01() || !tmp_8_fu_1030_p3.read().is_01())? sc_lv<31>(): (sc_bigint<31>(tmp_7_fu_1027_p1.read()) + sc_biguint<31>(tmp_8_fu_1030_p3.read()));
}

void lms::thread_ret_V_7_i_fu_522_p2() {
    ret_V_7_i_fu_522_p2 = (!lhs_V_3_7_i_fu_502_p3.read().is_01() || !rhs_V_7_i_cast_fu_510_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(lhs_V_3_7_i_fu_502_p3.read()) + sc_bigint<32>(rhs_V_7_i_cast_fu_510_p1.read()));
}

void lms::thread_ret_V_fu_554_p2() {
    ret_V_fu_554_p2 = (!lhs_V_fu_528_p1.read().is_01() || !rhs_V_1_cast_fu_550_p1.read().is_01())? sc_lv<17>(): (sc_bigint<17>(lhs_V_fu_528_p1.read()) - sc_bigint<17>(rhs_V_1_cast_fu_550_p1.read()));
}

void lms::thread_rhs_V_1_cast_fu_550_p1() {
    rhs_V_1_cast_fu_550_p1 = esl_sext<17,16>(rhs_V_fu_542_p3.read());
}

void lms::thread_rhs_V_7_i_cast_fu_510_p1() {
    rhs_V_7_i_cast_fu_510_p1 = esl_sext<32,30>(r_V_5_7_i_fu_1868_p2.read());
}

void lms::thread_rhs_V_fu_542_p3() {
    rhs_V_fu_542_p3 = esl_concat<14,2>(tmp_12_fu_532_p4.read(), ap_const_lv2_0);
}

void lms::thread_tmp_10_fu_493_p4() {
    tmp_10_fu_493_p4 = grp_fu_1858_p3.read().range(31, 18);
}

void lms::thread_tmp_12_fu_532_p4() {
    tmp_12_fu_532_p4 = ret_V_7_i_fu_522_p2.read().range(31, 18);
}

void lms::thread_tmp_13_fu_1787_p4() {
    tmp_13_fu_1787_p4 = ret_V_7_i_cast_fu_1037_p2.read().range(30, 18);
}

void lms::thread_tmp_1_fu_373_p3() {
    tmp_1_fu_373_p3 = esl_concat<13,18>(tmp_3_fu_356_p4.read(), ap_const_lv18_0);
}

void lms::thread_tmp_2_fu_393_p4() {
    tmp_2_fu_393_p4 = grp_fu_1822_p3.read().range(31, 18);
}

void lms::thread_tmp_3_fu_356_p4() {
    tmp_3_fu_356_p4 = grp_fu_1813_p3.read().range(30, 18);
}

void lms::thread_tmp_4_fu_418_p4() {
    tmp_4_fu_418_p4 = grp_fu_1831_p3.read().range(31, 18);
}

void lms::thread_tmp_5_fu_443_p4() {
    tmp_5_fu_443_p4 = grp_fu_1840_p3.read().range(31, 18);
}

void lms::thread_tmp_7_fu_1027_p1() {
    tmp_7_fu_1027_p1 = esl_sext<31,30>(r_V_5_7_i_reg_2144.read());
}

void lms::thread_tmp_8_fu_1030_p3() {
    tmp_8_fu_1030_p3 = esl_concat<13,18>(tmp_11_reg_2149.read(), ap_const_lv18_0);
}

void lms::thread_tmp_9_fu_468_p4() {
    tmp_9_fu_468_p4 = grp_fu_1849_p3.read().range(31, 18);
}

void lms::thread_tmp_fu_335_p4() {
    tmp_fu_335_p4 = r_V_5_i_fu_1806_p2.read().range(29, 18);
}

void lms::thread_y_V() {
    y_V = esl_concat<13,1>(tmp_13_fu_1787_p4.read(), ap_const_lv1_0);
}

void lms::thread_y_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        y_V_ap_vld = ap_const_logic_1;
    } else {
        y_V_ap_vld = ap_const_logic_0;
    }
}

void lms::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void lms::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"y_V\" :  \"" << y_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"y_V_ap_vld\" :  \"" << y_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xn_V\" :  \"" << xn_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dn_V\" :  \"" << dn_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

