# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/xn_noise_rom/xn_noise_rom.xci
# IP: The module: 'xn_noise_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/xn_noise_rom/xn_noise_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xn_noise_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/xn_noise_rom/xn_noise_rom.xci
# IP: The module: 'xn_noise_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/xn_noise_rom/xn_noise_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xn_noise_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
