// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="lms,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z007sclg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=35.509000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=72,HLS_SYN_FF=1996,HLS_SYN_LUT=105,HLS_VERSION=2018_3}" *)

module lms (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_V,
        y_V_ap_vld,
        xn_V,
        dn_V
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] y_V;
output   y_V_ap_vld;
input  [13:0] xn_V;
input  [13:0] dn_V;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_V_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg  signed [13:0] xk_V_62;
reg  signed [13:0] xk_V_61;
reg  signed [13:0] xk_V_60;
reg  signed [13:0] xk_V_59;
reg  signed [13:0] xk_V_58;
reg  signed [13:0] xk_V_57;
reg  signed [13:0] xk_V_56;
reg  signed [13:0] xk_V_55;
reg  signed [13:0] xk_V_54;
reg  signed [13:0] xk_V_53;
reg  signed [13:0] xk_V_52;
reg  signed [13:0] xk_V_51;
reg  signed [13:0] xk_V_50;
reg  signed [13:0] xk_V_49;
reg  signed [13:0] xk_V_48;
reg  signed [13:0] xk_V_47;
reg  signed [13:0] xk_V_46;
reg  signed [13:0] xk_V_45;
reg  signed [13:0] xk_V_44;
reg  signed [13:0] xk_V_43;
reg  signed [13:0] xk_V_42;
reg  signed [13:0] xk_V_41;
reg  signed [13:0] xk_V_40;
reg  signed [13:0] xk_V_39;
reg  signed [13:0] xk_V_38;
reg  signed [13:0] xk_V_37;
reg  signed [13:0] xk_V_36;
reg  signed [13:0] xk_V_35;
reg  signed [13:0] xk_V_34;
reg  signed [13:0] xk_V_33;
reg  signed [13:0] xk_V_32;
reg  signed [13:0] xk_V_31;
reg  signed [13:0] xk_V_30;
reg  signed [13:0] xk_V_29;
reg  signed [13:0] xk_V_28;
reg  signed [13:0] xk_V_27;
reg  signed [13:0] xk_V_26;
reg  signed [13:0] xk_V_25;
reg  signed [13:0] xk_V_24;
reg  signed [13:0] xk_V_23;
reg  signed [13:0] xk_V_22;
reg  signed [13:0] xk_V_21;
reg  signed [13:0] xk_V_20;
reg  signed [13:0] xk_V_19;
reg  signed [13:0] xk_V_18;
reg  signed [13:0] xk_V_17;
reg  signed [13:0] xk_V_16;
reg  signed [13:0] xk_V_15;
reg  signed [13:0] xk_V_14;
reg  signed [13:0] xk_V_13;
reg  signed [13:0] xk_V_12;
reg  signed [13:0] xk_V_11;
reg  signed [13:0] xk_V_10;
reg  signed [13:0] xk_V_9;
reg  signed [13:0] xk_V_8;
reg  signed [13:0] xk_V_7;
reg  signed [13:0] xk_V_6;
reg  signed [13:0] xk_V_5;
reg  signed [13:0] xk_V_4;
reg  signed [13:0] xk_V_3;
reg  signed [13:0] xk_V_2;
reg  signed [13:0] xk_V_1;
reg  signed [13:0] xk_V_0;
reg  signed [15:0] wk_V_0;
reg  signed [15:0] wk_V_1;
reg  signed [15:0] wk_V_2;
reg  signed [15:0] wk_V_3;
reg  signed [15:0] wk_V_4;
reg  signed [15:0] wk_V_5;
reg  signed [15:0] wk_V_6;
reg  signed [15:0] wk_V_7;
reg   [15:0] wk_V_8;
reg   [15:0] wk_V_9;
reg   [15:0] wk_V_10;
reg   [15:0] wk_V_11;
reg   [15:0] wk_V_12;
reg   [15:0] wk_V_13;
reg   [15:0] wk_V_14;
reg   [15:0] wk_V_15;
reg   [15:0] wk_V_16;
reg   [15:0] wk_V_17;
reg   [15:0] wk_V_18;
reg   [15:0] wk_V_19;
reg   [15:0] wk_V_20;
reg   [15:0] wk_V_21;
reg   [15:0] wk_V_22;
reg   [15:0] wk_V_23;
reg   [15:0] wk_V_24;
reg   [15:0] wk_V_25;
reg   [15:0] wk_V_26;
reg   [15:0] wk_V_27;
reg   [15:0] wk_V_28;
reg   [15:0] wk_V_29;
reg   [15:0] wk_V_30;
reg   [15:0] wk_V_31;
reg   [15:0] wk_V_32;
reg   [15:0] wk_V_33;
reg   [15:0] wk_V_34;
reg   [15:0] wk_V_35;
reg   [15:0] wk_V_36;
reg   [15:0] wk_V_37;
reg   [15:0] wk_V_38;
reg   [15:0] wk_V_39;
reg   [15:0] wk_V_40;
reg   [15:0] wk_V_41;
reg   [15:0] wk_V_42;
reg   [15:0] wk_V_43;
reg   [15:0] wk_V_44;
reg   [15:0] wk_V_45;
reg   [15:0] wk_V_46;
reg   [15:0] wk_V_47;
reg   [15:0] wk_V_48;
reg   [15:0] wk_V_49;
reg   [15:0] wk_V_50;
reg   [15:0] wk_V_51;
reg   [15:0] wk_V_52;
reg   [15:0] wk_V_53;
reg   [15:0] wk_V_54;
reg   [15:0] wk_V_55;
reg   [15:0] wk_V_56;
reg   [15:0] wk_V_57;
reg   [15:0] wk_V_58;
reg   [15:0] wk_V_59;
reg   [15:0] wk_V_60;
reg   [15:0] wk_V_61;
reg   [15:0] wk_V_62;
reg   [15:0] wk_V_63;
reg  signed [13:0] xk_V_6_load_reg_3835;
wire  signed [29:0] r_V_5_7_i_fu_3308_p2;
reg  signed [29:0] r_V_5_7_i_reg_3840;
reg   [12:0] tmp_11_reg_3845;
wire  signed [33:0] r_V_1_cast_fu_696_p1;
reg  signed [33:0] r_V_1_cast_reg_3850;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001;
wire  signed [29:0] r_V_5_i_fu_3246_p2;
wire   [11:0] tmp_fu_463_p4;
wire  signed [29:0] lhs_V_3_1_i_fu_472_p3;
wire  signed [30:0] grp_fu_3253_p3;
wire   [12:0] tmp_3_fu_484_p4;
wire  signed [30:0] tmp_1_fu_501_p3;
wire  signed [31:0] grp_fu_3262_p3;
wire   [13:0] tmp_2_fu_521_p4;
wire  signed [31:0] grp_fu_3271_p3;
wire   [13:0] tmp_4_fu_546_p4;
wire  signed [31:0] grp_fu_3280_p3;
wire   [13:0] tmp_5_fu_571_p4;
wire  signed [31:0] grp_fu_3289_p3;
wire   [13:0] tmp_9_fu_596_p4;
wire  signed [31:0] grp_fu_3298_p3;
wire   [13:0] tmp_10_fu_621_p4;
wire   [31:0] lhs_V_3_7_i_fu_630_p3;
wire  signed [31:0] rhs_V_7_i_cast_fu_638_p1;
wire   [31:0] ret_V_7_i_fu_650_p2;
wire   [13:0] tmp_12_fu_660_p4;
wire   [15:0] rhs_V_fu_670_p3;
wire  signed [16:0] lhs_V_fu_656_p1;
wire  signed [16:0] rhs_V_1_cast_fu_678_p1;
wire   [16:0] ret_V_fu_682_p2;
wire   [19:0] r_V_fu_688_p3;
wire  signed [15:0] lhs_V_2_fu_704_p1;
wire  signed [35:0] grp_fu_3315_p3;
wire  signed [15:0] lhs_V_2_1_fu_731_p1;
wire  signed [35:0] grp_fu_3324_p3;
wire  signed [15:0] lhs_V_2_2_fu_758_p1;
wire  signed [35:0] grp_fu_3333_p3;
wire  signed [15:0] lhs_V_2_3_fu_785_p1;
wire  signed [35:0] grp_fu_3342_p3;
wire  signed [15:0] lhs_V_2_4_fu_812_p1;
wire  signed [35:0] grp_fu_3351_p3;
wire  signed [15:0] lhs_V_2_5_fu_839_p1;
wire  signed [35:0] grp_fu_3360_p3;
wire  signed [15:0] lhs_V_2_6_fu_866_p1;
wire  signed [35:0] grp_fu_3369_p3;
wire  signed [15:0] lhs_V_2_7_fu_893_p1;
wire  signed [35:0] grp_fu_3378_p3;
wire  signed [30:0] tmp_7_fu_1475_p1;
wire   [30:0] tmp_8_fu_1478_p3;
wire  signed [35:0] grp_fu_3387_p3;
wire  signed [35:0] grp_fu_3395_p3;
wire  signed [35:0] grp_fu_3403_p3;
wire  signed [35:0] grp_fu_3411_p3;
wire  signed [35:0] grp_fu_3419_p3;
wire  signed [35:0] grp_fu_3427_p3;
wire  signed [35:0] grp_fu_3435_p3;
wire  signed [35:0] grp_fu_3443_p3;
wire  signed [35:0] grp_fu_3451_p3;
wire  signed [35:0] grp_fu_3459_p3;
wire  signed [35:0] grp_fu_3467_p3;
wire  signed [35:0] grp_fu_3475_p3;
wire  signed [35:0] grp_fu_3483_p3;
wire  signed [35:0] grp_fu_3491_p3;
wire  signed [35:0] grp_fu_3499_p3;
wire  signed [35:0] grp_fu_3507_p3;
wire  signed [35:0] grp_fu_3515_p3;
wire  signed [35:0] grp_fu_3523_p3;
wire  signed [35:0] grp_fu_3531_p3;
wire  signed [35:0] grp_fu_3539_p3;
wire  signed [35:0] grp_fu_3547_p3;
wire  signed [35:0] grp_fu_3555_p3;
wire  signed [35:0] grp_fu_3563_p3;
wire  signed [35:0] grp_fu_3571_p3;
wire  signed [35:0] grp_fu_3579_p3;
wire  signed [35:0] grp_fu_3587_p3;
wire  signed [35:0] grp_fu_3595_p3;
wire  signed [35:0] grp_fu_3603_p3;
wire  signed [35:0] grp_fu_3611_p3;
wire  signed [35:0] grp_fu_3619_p3;
wire  signed [35:0] grp_fu_3627_p3;
wire  signed [35:0] grp_fu_3635_p3;
wire  signed [35:0] grp_fu_3643_p3;
wire  signed [35:0] grp_fu_3651_p3;
wire  signed [35:0] grp_fu_3659_p3;
wire  signed [35:0] grp_fu_3667_p3;
wire  signed [35:0] grp_fu_3675_p3;
wire  signed [35:0] grp_fu_3683_p3;
wire  signed [35:0] grp_fu_3691_p3;
wire  signed [35:0] grp_fu_3699_p3;
wire  signed [35:0] grp_fu_3707_p3;
wire  signed [35:0] grp_fu_3715_p3;
wire  signed [35:0] grp_fu_3723_p3;
wire  signed [35:0] grp_fu_3731_p3;
wire  signed [35:0] grp_fu_3739_p3;
wire  signed [35:0] grp_fu_3747_p3;
wire  signed [35:0] grp_fu_3755_p3;
wire  signed [35:0] grp_fu_3763_p3;
wire  signed [35:0] grp_fu_3771_p3;
wire  signed [35:0] grp_fu_3779_p3;
wire  signed [35:0] grp_fu_3787_p3;
wire  signed [35:0] grp_fu_3795_p3;
wire  signed [35:0] grp_fu_3803_p3;
wire  signed [35:0] grp_fu_3811_p3;
wire  signed [35:0] grp_fu_3819_p3;
wire  signed [35:0] grp_fu_3827_p3;
wire   [30:0] ret_V_7_i_cast_fu_1485_p2;
wire   [12:0] tmp_13_fu_3227_p4;
wire   [31:0] grp_fu_3271_p2;
wire   [31:0] grp_fu_3280_p2;
wire   [31:0] grp_fu_3289_p2;
wire   [31:0] grp_fu_3298_p2;
wire  signed [19:0] grp_fu_3315_p0;
wire   [35:0] grp_fu_3315_p2;
wire  signed [19:0] grp_fu_3324_p0;
wire   [35:0] grp_fu_3324_p2;
wire  signed [19:0] grp_fu_3333_p0;
wire   [35:0] grp_fu_3333_p2;
wire  signed [19:0] grp_fu_3342_p0;
wire   [35:0] grp_fu_3342_p2;
wire  signed [19:0] grp_fu_3351_p0;
wire   [35:0] grp_fu_3351_p2;
wire  signed [19:0] grp_fu_3360_p0;
wire   [35:0] grp_fu_3360_p2;
wire  signed [19:0] grp_fu_3369_p0;
wire   [35:0] grp_fu_3369_p2;
wire  signed [19:0] grp_fu_3378_p0;
wire   [35:0] grp_fu_3378_p2;
wire  signed [19:0] grp_fu_3387_p0;
wire   [35:0] grp_fu_3387_p2;
wire  signed [19:0] grp_fu_3395_p0;
wire   [35:0] grp_fu_3395_p2;
wire  signed [19:0] grp_fu_3403_p0;
wire   [35:0] grp_fu_3403_p2;
wire  signed [19:0] grp_fu_3411_p0;
wire   [35:0] grp_fu_3411_p2;
wire  signed [19:0] grp_fu_3419_p0;
wire   [35:0] grp_fu_3419_p2;
wire  signed [19:0] grp_fu_3427_p0;
wire   [35:0] grp_fu_3427_p2;
wire  signed [19:0] grp_fu_3435_p0;
wire   [35:0] grp_fu_3435_p2;
wire  signed [19:0] grp_fu_3443_p0;
wire   [35:0] grp_fu_3443_p2;
wire  signed [19:0] grp_fu_3451_p0;
wire   [35:0] grp_fu_3451_p2;
wire  signed [19:0] grp_fu_3459_p0;
wire   [35:0] grp_fu_3459_p2;
wire  signed [19:0] grp_fu_3467_p0;
wire   [35:0] grp_fu_3467_p2;
wire  signed [19:0] grp_fu_3475_p0;
wire   [35:0] grp_fu_3475_p2;
wire  signed [19:0] grp_fu_3483_p0;
wire   [35:0] grp_fu_3483_p2;
wire  signed [19:0] grp_fu_3491_p0;
wire   [35:0] grp_fu_3491_p2;
wire  signed [19:0] grp_fu_3499_p0;
wire   [35:0] grp_fu_3499_p2;
wire  signed [19:0] grp_fu_3507_p0;
wire   [35:0] grp_fu_3507_p2;
wire  signed [19:0] grp_fu_3515_p0;
wire   [35:0] grp_fu_3515_p2;
wire  signed [19:0] grp_fu_3523_p0;
wire   [35:0] grp_fu_3523_p2;
wire  signed [19:0] grp_fu_3531_p0;
wire   [35:0] grp_fu_3531_p2;
wire  signed [19:0] grp_fu_3539_p0;
wire   [35:0] grp_fu_3539_p2;
wire  signed [19:0] grp_fu_3547_p0;
wire   [35:0] grp_fu_3547_p2;
wire  signed [19:0] grp_fu_3555_p0;
wire   [35:0] grp_fu_3555_p2;
wire  signed [19:0] grp_fu_3563_p0;
wire   [35:0] grp_fu_3563_p2;
wire  signed [19:0] grp_fu_3571_p0;
wire   [35:0] grp_fu_3571_p2;
wire  signed [19:0] grp_fu_3579_p0;
wire   [35:0] grp_fu_3579_p2;
wire  signed [19:0] grp_fu_3587_p0;
wire   [35:0] grp_fu_3587_p2;
wire  signed [19:0] grp_fu_3595_p0;
wire   [35:0] grp_fu_3595_p2;
wire  signed [19:0] grp_fu_3603_p0;
wire   [35:0] grp_fu_3603_p2;
wire  signed [19:0] grp_fu_3611_p0;
wire   [35:0] grp_fu_3611_p2;
wire  signed [19:0] grp_fu_3619_p0;
wire   [35:0] grp_fu_3619_p2;
wire  signed [19:0] grp_fu_3627_p0;
wire   [35:0] grp_fu_3627_p2;
wire  signed [19:0] grp_fu_3635_p0;
wire   [35:0] grp_fu_3635_p2;
wire  signed [19:0] grp_fu_3643_p0;
wire   [35:0] grp_fu_3643_p2;
wire  signed [19:0] grp_fu_3651_p0;
wire   [35:0] grp_fu_3651_p2;
wire  signed [19:0] grp_fu_3659_p0;
wire   [35:0] grp_fu_3659_p2;
wire  signed [19:0] grp_fu_3667_p0;
wire   [35:0] grp_fu_3667_p2;
wire  signed [19:0] grp_fu_3675_p0;
wire   [35:0] grp_fu_3675_p2;
wire  signed [19:0] grp_fu_3683_p0;
wire   [35:0] grp_fu_3683_p2;
wire  signed [19:0] grp_fu_3691_p0;
wire   [35:0] grp_fu_3691_p2;
wire  signed [19:0] grp_fu_3699_p0;
wire   [35:0] grp_fu_3699_p2;
wire  signed [19:0] grp_fu_3707_p0;
wire   [35:0] grp_fu_3707_p2;
wire  signed [19:0] grp_fu_3715_p0;
wire   [35:0] grp_fu_3715_p2;
wire  signed [19:0] grp_fu_3723_p0;
wire   [35:0] grp_fu_3723_p2;
wire  signed [19:0] grp_fu_3731_p0;
wire   [35:0] grp_fu_3731_p2;
wire  signed [19:0] grp_fu_3739_p0;
wire   [35:0] grp_fu_3739_p2;
wire  signed [19:0] grp_fu_3747_p0;
wire   [35:0] grp_fu_3747_p2;
wire  signed [19:0] grp_fu_3755_p0;
wire   [35:0] grp_fu_3755_p2;
wire  signed [19:0] grp_fu_3763_p0;
wire   [35:0] grp_fu_3763_p2;
wire  signed [19:0] grp_fu_3771_p0;
wire   [35:0] grp_fu_3771_p2;
wire  signed [19:0] grp_fu_3779_p0;
wire   [35:0] grp_fu_3779_p2;
wire  signed [19:0] grp_fu_3787_p0;
wire   [35:0] grp_fu_3787_p2;
wire  signed [19:0] grp_fu_3795_p0;
wire   [35:0] grp_fu_3795_p2;
wire  signed [19:0] grp_fu_3803_p0;
wire   [35:0] grp_fu_3803_p2;
wire  signed [19:0] grp_fu_3811_p0;
wire   [35:0] grp_fu_3811_p2;
wire  signed [19:0] grp_fu_3819_p0;
wire   [35:0] grp_fu_3819_p2;
wire  signed [19:0] grp_fu_3827_p0;
wire   [35:0] grp_fu_3827_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 xk_V_62 = 14'd0;
#0 xk_V_61 = 14'd0;
#0 xk_V_60 = 14'd0;
#0 xk_V_59 = 14'd0;
#0 xk_V_58 = 14'd0;
#0 xk_V_57 = 14'd0;
#0 xk_V_56 = 14'd0;
#0 xk_V_55 = 14'd0;
#0 xk_V_54 = 14'd0;
#0 xk_V_53 = 14'd0;
#0 xk_V_52 = 14'd0;
#0 xk_V_51 = 14'd0;
#0 xk_V_50 = 14'd0;
#0 xk_V_49 = 14'd0;
#0 xk_V_48 = 14'd0;
#0 xk_V_47 = 14'd0;
#0 xk_V_46 = 14'd0;
#0 xk_V_45 = 14'd0;
#0 xk_V_44 = 14'd0;
#0 xk_V_43 = 14'd0;
#0 xk_V_42 = 14'd0;
#0 xk_V_41 = 14'd0;
#0 xk_V_40 = 14'd0;
#0 xk_V_39 = 14'd0;
#0 xk_V_38 = 14'd0;
#0 xk_V_37 = 14'd0;
#0 xk_V_36 = 14'd0;
#0 xk_V_35 = 14'd0;
#0 xk_V_34 = 14'd0;
#0 xk_V_33 = 14'd0;
#0 xk_V_32 = 14'd0;
#0 xk_V_31 = 14'd0;
#0 xk_V_30 = 14'd0;
#0 xk_V_29 = 14'd0;
#0 xk_V_28 = 14'd0;
#0 xk_V_27 = 14'd0;
#0 xk_V_26 = 14'd0;
#0 xk_V_25 = 14'd0;
#0 xk_V_24 = 14'd0;
#0 xk_V_23 = 14'd0;
#0 xk_V_22 = 14'd0;
#0 xk_V_21 = 14'd0;
#0 xk_V_20 = 14'd0;
#0 xk_V_19 = 14'd0;
#0 xk_V_18 = 14'd0;
#0 xk_V_17 = 14'd0;
#0 xk_V_16 = 14'd0;
#0 xk_V_15 = 14'd0;
#0 xk_V_14 = 14'd0;
#0 xk_V_13 = 14'd0;
#0 xk_V_12 = 14'd0;
#0 xk_V_11 = 14'd0;
#0 xk_V_10 = 14'd0;
#0 xk_V_9 = 14'd0;
#0 xk_V_8 = 14'd0;
#0 xk_V_7 = 14'd0;
#0 xk_V_6 = 14'd0;
#0 xk_V_5 = 14'd0;
#0 xk_V_4 = 14'd0;
#0 xk_V_3 = 14'd0;
#0 xk_V_2 = 14'd0;
#0 xk_V_1 = 14'd0;
#0 xk_V_0 = 14'd0;
#0 wk_V_0 = 16'd0;
#0 wk_V_1 = 16'd0;
#0 wk_V_2 = 16'd0;
#0 wk_V_3 = 16'd0;
#0 wk_V_4 = 16'd0;
#0 wk_V_5 = 16'd0;
#0 wk_V_6 = 16'd0;
#0 wk_V_7 = 16'd0;
#0 wk_V_8 = 16'd0;
#0 wk_V_9 = 16'd0;
#0 wk_V_10 = 16'd0;
#0 wk_V_11 = 16'd0;
#0 wk_V_12 = 16'd0;
#0 wk_V_13 = 16'd0;
#0 wk_V_14 = 16'd0;
#0 wk_V_15 = 16'd0;
#0 wk_V_16 = 16'd0;
#0 wk_V_17 = 16'd0;
#0 wk_V_18 = 16'd0;
#0 wk_V_19 = 16'd0;
#0 wk_V_20 = 16'd0;
#0 wk_V_21 = 16'd0;
#0 wk_V_22 = 16'd0;
#0 wk_V_23 = 16'd0;
#0 wk_V_24 = 16'd0;
#0 wk_V_25 = 16'd0;
#0 wk_V_26 = 16'd0;
#0 wk_V_27 = 16'd0;
#0 wk_V_28 = 16'd0;
#0 wk_V_29 = 16'd0;
#0 wk_V_30 = 16'd0;
#0 wk_V_31 = 16'd0;
#0 wk_V_32 = 16'd0;
#0 wk_V_33 = 16'd0;
#0 wk_V_34 = 16'd0;
#0 wk_V_35 = 16'd0;
#0 wk_V_36 = 16'd0;
#0 wk_V_37 = 16'd0;
#0 wk_V_38 = 16'd0;
#0 wk_V_39 = 16'd0;
#0 wk_V_40 = 16'd0;
#0 wk_V_41 = 16'd0;
#0 wk_V_42 = 16'd0;
#0 wk_V_43 = 16'd0;
#0 wk_V_44 = 16'd0;
#0 wk_V_45 = 16'd0;
#0 wk_V_46 = 16'd0;
#0 wk_V_47 = 16'd0;
#0 wk_V_48 = 16'd0;
#0 wk_V_49 = 16'd0;
#0 wk_V_50 = 16'd0;
#0 wk_V_51 = 16'd0;
#0 wk_V_52 = 16'd0;
#0 wk_V_53 = 16'd0;
#0 wk_V_54 = 16'd0;
#0 wk_V_55 = 16'd0;
#0 wk_V_56 = 16'd0;
#0 wk_V_57 = 16'd0;
#0 wk_V_58 = 16'd0;
#0 wk_V_59 = 16'd0;
#0 wk_V_60 = 16'd0;
#0 wk_V_61 = 16'd0;
#0 wk_V_62 = 16'd0;
#0 wk_V_63 = 16'd0;
end

lms_mul_mul_16s_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
lms_mul_mul_16s_1bkb_U1(
    .din0(wk_V_0),
    .din1(xn_V),
    .dout(r_V_5_i_fu_3246_p2)
);

lms_mac_muladd_16cud #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 30 ),
    .dout_WIDTH( 31 ))
lms_mac_muladd_16cud_U2(
    .din0(wk_V_1),
    .din1(xk_V_0),
    .din2(lhs_V_3_1_i_fu_472_p3),
    .dout(grp_fu_3253_p3)
);

lms_mac_muladd_16dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 32 ))
lms_mac_muladd_16dEe_U3(
    .din0(wk_V_2),
    .din1(xk_V_1),
    .din2(tmp_1_fu_501_p3),
    .dout(grp_fu_3262_p3)
);

lms_mac_muladd_16eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lms_mac_muladd_16eOg_U4(
    .din0(wk_V_3),
    .din1(xk_V_2),
    .din2(grp_fu_3271_p2),
    .dout(grp_fu_3271_p3)
);

lms_mac_muladd_16eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lms_mac_muladd_16eOg_U5(
    .din0(wk_V_4),
    .din1(xk_V_3),
    .din2(grp_fu_3280_p2),
    .dout(grp_fu_3280_p3)
);

lms_mac_muladd_16eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lms_mac_muladd_16eOg_U6(
    .din0(wk_V_5),
    .din1(xk_V_4),
    .din2(grp_fu_3289_p2),
    .dout(grp_fu_3289_p3)
);

lms_mac_muladd_16eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
lms_mac_muladd_16eOg_U7(
    .din0(wk_V_6),
    .din1(xk_V_5),
    .din2(grp_fu_3298_p2),
    .dout(grp_fu_3298_p3)
);

lms_mul_mul_16s_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 14 ),
    .dout_WIDTH( 30 ))
lms_mul_mul_16s_1bkb_U8(
    .din0(wk_V_7),
    .din1(xk_V_6),
    .dout(r_V_5_7_i_fu_3308_p2)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U9(
    .din0(grp_fu_3315_p0),
    .din1(xn_V),
    .din2(grp_fu_3315_p2),
    .dout(grp_fu_3315_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U10(
    .din0(grp_fu_3324_p0),
    .din1(xk_V_0),
    .din2(grp_fu_3324_p2),
    .dout(grp_fu_3324_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U11(
    .din0(grp_fu_3333_p0),
    .din1(xk_V_1),
    .din2(grp_fu_3333_p2),
    .dout(grp_fu_3333_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U12(
    .din0(grp_fu_3342_p0),
    .din1(xk_V_2),
    .din2(grp_fu_3342_p2),
    .dout(grp_fu_3342_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U13(
    .din0(grp_fu_3351_p0),
    .din1(xk_V_3),
    .din2(grp_fu_3351_p2),
    .dout(grp_fu_3351_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U14(
    .din0(grp_fu_3360_p0),
    .din1(xk_V_4),
    .din2(grp_fu_3360_p2),
    .dout(grp_fu_3360_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U15(
    .din0(grp_fu_3369_p0),
    .din1(xk_V_5),
    .din2(grp_fu_3369_p2),
    .dout(grp_fu_3369_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U16(
    .din0(grp_fu_3378_p0),
    .din1(xk_V_6),
    .din2(grp_fu_3378_p2),
    .dout(grp_fu_3378_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U17(
    .din0(grp_fu_3387_p0),
    .din1(xk_V_7),
    .din2(grp_fu_3387_p2),
    .dout(grp_fu_3387_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U18(
    .din0(grp_fu_3395_p0),
    .din1(xk_V_8),
    .din2(grp_fu_3395_p2),
    .dout(grp_fu_3395_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U19(
    .din0(grp_fu_3403_p0),
    .din1(xk_V_9),
    .din2(grp_fu_3403_p2),
    .dout(grp_fu_3403_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U20(
    .din0(grp_fu_3411_p0),
    .din1(xk_V_10),
    .din2(grp_fu_3411_p2),
    .dout(grp_fu_3411_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U21(
    .din0(grp_fu_3419_p0),
    .din1(xk_V_11),
    .din2(grp_fu_3419_p2),
    .dout(grp_fu_3419_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U22(
    .din0(grp_fu_3427_p0),
    .din1(xk_V_12),
    .din2(grp_fu_3427_p2),
    .dout(grp_fu_3427_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U23(
    .din0(grp_fu_3435_p0),
    .din1(xk_V_13),
    .din2(grp_fu_3435_p2),
    .dout(grp_fu_3435_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U24(
    .din0(grp_fu_3443_p0),
    .din1(xk_V_14),
    .din2(grp_fu_3443_p2),
    .dout(grp_fu_3443_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U25(
    .din0(grp_fu_3451_p0),
    .din1(xk_V_15),
    .din2(grp_fu_3451_p2),
    .dout(grp_fu_3451_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U26(
    .din0(grp_fu_3459_p0),
    .din1(xk_V_16),
    .din2(grp_fu_3459_p2),
    .dout(grp_fu_3459_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U27(
    .din0(grp_fu_3467_p0),
    .din1(xk_V_17),
    .din2(grp_fu_3467_p2),
    .dout(grp_fu_3467_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U28(
    .din0(grp_fu_3475_p0),
    .din1(xk_V_18),
    .din2(grp_fu_3475_p2),
    .dout(grp_fu_3475_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U29(
    .din0(grp_fu_3483_p0),
    .din1(xk_V_19),
    .din2(grp_fu_3483_p2),
    .dout(grp_fu_3483_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U30(
    .din0(grp_fu_3491_p0),
    .din1(xk_V_20),
    .din2(grp_fu_3491_p2),
    .dout(grp_fu_3491_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U31(
    .din0(grp_fu_3499_p0),
    .din1(xk_V_21),
    .din2(grp_fu_3499_p2),
    .dout(grp_fu_3499_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U32(
    .din0(grp_fu_3507_p0),
    .din1(xk_V_22),
    .din2(grp_fu_3507_p2),
    .dout(grp_fu_3507_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U33(
    .din0(grp_fu_3515_p0),
    .din1(xk_V_23),
    .din2(grp_fu_3515_p2),
    .dout(grp_fu_3515_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U34(
    .din0(grp_fu_3523_p0),
    .din1(xk_V_24),
    .din2(grp_fu_3523_p2),
    .dout(grp_fu_3523_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U35(
    .din0(grp_fu_3531_p0),
    .din1(xk_V_25),
    .din2(grp_fu_3531_p2),
    .dout(grp_fu_3531_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U36(
    .din0(grp_fu_3539_p0),
    .din1(xk_V_26),
    .din2(grp_fu_3539_p2),
    .dout(grp_fu_3539_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U37(
    .din0(grp_fu_3547_p0),
    .din1(xk_V_27),
    .din2(grp_fu_3547_p2),
    .dout(grp_fu_3547_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U38(
    .din0(grp_fu_3555_p0),
    .din1(xk_V_28),
    .din2(grp_fu_3555_p2),
    .dout(grp_fu_3555_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U39(
    .din0(grp_fu_3563_p0),
    .din1(xk_V_29),
    .din2(grp_fu_3563_p2),
    .dout(grp_fu_3563_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U40(
    .din0(grp_fu_3571_p0),
    .din1(xk_V_30),
    .din2(grp_fu_3571_p2),
    .dout(grp_fu_3571_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U41(
    .din0(grp_fu_3579_p0),
    .din1(xk_V_31),
    .din2(grp_fu_3579_p2),
    .dout(grp_fu_3579_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U42(
    .din0(grp_fu_3587_p0),
    .din1(xk_V_32),
    .din2(grp_fu_3587_p2),
    .dout(grp_fu_3587_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U43(
    .din0(grp_fu_3595_p0),
    .din1(xk_V_33),
    .din2(grp_fu_3595_p2),
    .dout(grp_fu_3595_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U44(
    .din0(grp_fu_3603_p0),
    .din1(xk_V_34),
    .din2(grp_fu_3603_p2),
    .dout(grp_fu_3603_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U45(
    .din0(grp_fu_3611_p0),
    .din1(xk_V_35),
    .din2(grp_fu_3611_p2),
    .dout(grp_fu_3611_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U46(
    .din0(grp_fu_3619_p0),
    .din1(xk_V_36),
    .din2(grp_fu_3619_p2),
    .dout(grp_fu_3619_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U47(
    .din0(grp_fu_3627_p0),
    .din1(xk_V_37),
    .din2(grp_fu_3627_p2),
    .dout(grp_fu_3627_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U48(
    .din0(grp_fu_3635_p0),
    .din1(xk_V_38),
    .din2(grp_fu_3635_p2),
    .dout(grp_fu_3635_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U49(
    .din0(grp_fu_3643_p0),
    .din1(xk_V_39),
    .din2(grp_fu_3643_p2),
    .dout(grp_fu_3643_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U50(
    .din0(grp_fu_3651_p0),
    .din1(xk_V_40),
    .din2(grp_fu_3651_p2),
    .dout(grp_fu_3651_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U51(
    .din0(grp_fu_3659_p0),
    .din1(xk_V_41),
    .din2(grp_fu_3659_p2),
    .dout(grp_fu_3659_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U52(
    .din0(grp_fu_3667_p0),
    .din1(xk_V_42),
    .din2(grp_fu_3667_p2),
    .dout(grp_fu_3667_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U53(
    .din0(grp_fu_3675_p0),
    .din1(xk_V_43),
    .din2(grp_fu_3675_p2),
    .dout(grp_fu_3675_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U54(
    .din0(grp_fu_3683_p0),
    .din1(xk_V_44),
    .din2(grp_fu_3683_p2),
    .dout(grp_fu_3683_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U55(
    .din0(grp_fu_3691_p0),
    .din1(xk_V_45),
    .din2(grp_fu_3691_p2),
    .dout(grp_fu_3691_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U56(
    .din0(grp_fu_3699_p0),
    .din1(xk_V_46),
    .din2(grp_fu_3699_p2),
    .dout(grp_fu_3699_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U57(
    .din0(grp_fu_3707_p0),
    .din1(xk_V_47),
    .din2(grp_fu_3707_p2),
    .dout(grp_fu_3707_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U58(
    .din0(grp_fu_3715_p0),
    .din1(xk_V_48),
    .din2(grp_fu_3715_p2),
    .dout(grp_fu_3715_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U59(
    .din0(grp_fu_3723_p0),
    .din1(xk_V_49),
    .din2(grp_fu_3723_p2),
    .dout(grp_fu_3723_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U60(
    .din0(grp_fu_3731_p0),
    .din1(xk_V_50),
    .din2(grp_fu_3731_p2),
    .dout(grp_fu_3731_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U61(
    .din0(grp_fu_3739_p0),
    .din1(xk_V_51),
    .din2(grp_fu_3739_p2),
    .dout(grp_fu_3739_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U62(
    .din0(grp_fu_3747_p0),
    .din1(xk_V_52),
    .din2(grp_fu_3747_p2),
    .dout(grp_fu_3747_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U63(
    .din0(grp_fu_3755_p0),
    .din1(xk_V_53),
    .din2(grp_fu_3755_p2),
    .dout(grp_fu_3755_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U64(
    .din0(grp_fu_3763_p0),
    .din1(xk_V_54),
    .din2(grp_fu_3763_p2),
    .dout(grp_fu_3763_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U65(
    .din0(grp_fu_3771_p0),
    .din1(xk_V_55),
    .din2(grp_fu_3771_p2),
    .dout(grp_fu_3771_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U66(
    .din0(grp_fu_3779_p0),
    .din1(xk_V_56),
    .din2(grp_fu_3779_p2),
    .dout(grp_fu_3779_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U67(
    .din0(grp_fu_3787_p0),
    .din1(xk_V_57),
    .din2(grp_fu_3787_p2),
    .dout(grp_fu_3787_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U68(
    .din0(grp_fu_3795_p0),
    .din1(xk_V_58),
    .din2(grp_fu_3795_p2),
    .dout(grp_fu_3795_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U69(
    .din0(grp_fu_3803_p0),
    .din1(xk_V_59),
    .din2(grp_fu_3803_p2),
    .dout(grp_fu_3803_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U70(
    .din0(grp_fu_3811_p0),
    .din1(xk_V_60),
    .din2(grp_fu_3811_p2),
    .dout(grp_fu_3811_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U71(
    .din0(grp_fu_3819_p0),
    .din1(xk_V_61),
    .din2(grp_fu_3819_p2),
    .dout(grp_fu_3819_p3)
);

lms_mac_muladd_20fYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 20 ),
    .din1_WIDTH( 14 ),
    .din2_WIDTH( 36 ),
    .dout_WIDTH( 36 ))
lms_mac_muladd_20fYi_U72(
    .din0(grp_fu_3827_p0),
    .din1(xk_V_62),
    .din2(grp_fu_3827_p2),
    .dout(grp_fu_3827_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_V_1_cast_reg_3850[33 : 3] <= r_V_1_cast_fu_696_p1[33 : 3];
        r_V_5_7_i_reg_3840 <= r_V_5_7_i_fu_3308_p2;
        tmp_11_reg_3845 <= {{grp_fu_3298_p3[30:18]}};
        xk_V_6_load_reg_3835 <= xk_V_6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wk_V_0 <= {{grp_fu_3315_p3[35:20]}};
        wk_V_1 <= {{grp_fu_3324_p3[35:20]}};
        wk_V_2 <= {{grp_fu_3333_p3[35:20]}};
        wk_V_3 <= {{grp_fu_3342_p3[35:20]}};
        wk_V_4 <= {{grp_fu_3351_p3[35:20]}};
        wk_V_5 <= {{grp_fu_3360_p3[35:20]}};
        wk_V_6 <= {{grp_fu_3369_p3[35:20]}};
        wk_V_7 <= {{grp_fu_3378_p3[35:20]}};
        xk_V_0 <= xn_V;
        xk_V_1 <= xk_V_0;
        xk_V_2 <= xk_V_1;
        xk_V_3 <= xk_V_2;
        xk_V_4 <= xk_V_3;
        xk_V_5 <= xk_V_4;
        xk_V_6 <= xk_V_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        wk_V_10 <= {{grp_fu_3403_p3[35:20]}};
        wk_V_11 <= {{grp_fu_3411_p3[35:20]}};
        wk_V_12 <= {{grp_fu_3419_p3[35:20]}};
        wk_V_13 <= {{grp_fu_3427_p3[35:20]}};
        wk_V_14 <= {{grp_fu_3435_p3[35:20]}};
        wk_V_15 <= {{grp_fu_3443_p3[35:20]}};
        wk_V_16 <= {{grp_fu_3451_p3[35:20]}};
        wk_V_17 <= {{grp_fu_3459_p3[35:20]}};
        wk_V_18 <= {{grp_fu_3467_p3[35:20]}};
        wk_V_19 <= {{grp_fu_3475_p3[35:20]}};
        wk_V_20 <= {{grp_fu_3483_p3[35:20]}};
        wk_V_21 <= {{grp_fu_3491_p3[35:20]}};
        wk_V_22 <= {{grp_fu_3499_p3[35:20]}};
        wk_V_23 <= {{grp_fu_3507_p3[35:20]}};
        wk_V_24 <= {{grp_fu_3515_p3[35:20]}};
        wk_V_25 <= {{grp_fu_3523_p3[35:20]}};
        wk_V_26 <= {{grp_fu_3531_p3[35:20]}};
        wk_V_27 <= {{grp_fu_3539_p3[35:20]}};
        wk_V_28 <= {{grp_fu_3547_p3[35:20]}};
        wk_V_29 <= {{grp_fu_3555_p3[35:20]}};
        wk_V_30 <= {{grp_fu_3563_p3[35:20]}};
        wk_V_31 <= {{grp_fu_3571_p3[35:20]}};
        wk_V_32 <= {{grp_fu_3579_p3[35:20]}};
        wk_V_33 <= {{grp_fu_3587_p3[35:20]}};
        wk_V_34 <= {{grp_fu_3595_p3[35:20]}};
        wk_V_35 <= {{grp_fu_3603_p3[35:20]}};
        wk_V_36 <= {{grp_fu_3611_p3[35:20]}};
        wk_V_37 <= {{grp_fu_3619_p3[35:20]}};
        wk_V_38 <= {{grp_fu_3627_p3[35:20]}};
        wk_V_39 <= {{grp_fu_3635_p3[35:20]}};
        wk_V_40 <= {{grp_fu_3643_p3[35:20]}};
        wk_V_41 <= {{grp_fu_3651_p3[35:20]}};
        wk_V_42 <= {{grp_fu_3659_p3[35:20]}};
        wk_V_43 <= {{grp_fu_3667_p3[35:20]}};
        wk_V_44 <= {{grp_fu_3675_p3[35:20]}};
        wk_V_45 <= {{grp_fu_3683_p3[35:20]}};
        wk_V_46 <= {{grp_fu_3691_p3[35:20]}};
        wk_V_47 <= {{grp_fu_3699_p3[35:20]}};
        wk_V_48 <= {{grp_fu_3707_p3[35:20]}};
        wk_V_49 <= {{grp_fu_3715_p3[35:20]}};
        wk_V_50 <= {{grp_fu_3723_p3[35:20]}};
        wk_V_51 <= {{grp_fu_3731_p3[35:20]}};
        wk_V_52 <= {{grp_fu_3739_p3[35:20]}};
        wk_V_53 <= {{grp_fu_3747_p3[35:20]}};
        wk_V_54 <= {{grp_fu_3755_p3[35:20]}};
        wk_V_55 <= {{grp_fu_3763_p3[35:20]}};
        wk_V_56 <= {{grp_fu_3771_p3[35:20]}};
        wk_V_57 <= {{grp_fu_3779_p3[35:20]}};
        wk_V_58 <= {{grp_fu_3787_p3[35:20]}};
        wk_V_59 <= {{grp_fu_3795_p3[35:20]}};
        wk_V_60 <= {{grp_fu_3803_p3[35:20]}};
        wk_V_61 <= {{grp_fu_3811_p3[35:20]}};
        wk_V_62 <= {{grp_fu_3819_p3[35:20]}};
        wk_V_63 <= {{grp_fu_3827_p3[35:20]}};
        wk_V_8 <= {{grp_fu_3387_p3[35:20]}};
        wk_V_9 <= {{grp_fu_3395_p3[35:20]}};
        xk_V_10 <= xk_V_9;
        xk_V_11 <= xk_V_10;
        xk_V_12 <= xk_V_11;
        xk_V_13 <= xk_V_12;
        xk_V_14 <= xk_V_13;
        xk_V_15 <= xk_V_14;
        xk_V_16 <= xk_V_15;
        xk_V_17 <= xk_V_16;
        xk_V_18 <= xk_V_17;
        xk_V_19 <= xk_V_18;
        xk_V_20 <= xk_V_19;
        xk_V_21 <= xk_V_20;
        xk_V_22 <= xk_V_21;
        xk_V_23 <= xk_V_22;
        xk_V_24 <= xk_V_23;
        xk_V_25 <= xk_V_24;
        xk_V_26 <= xk_V_25;
        xk_V_27 <= xk_V_26;
        xk_V_28 <= xk_V_27;
        xk_V_29 <= xk_V_28;
        xk_V_30 <= xk_V_29;
        xk_V_31 <= xk_V_30;
        xk_V_32 <= xk_V_31;
        xk_V_33 <= xk_V_32;
        xk_V_34 <= xk_V_33;
        xk_V_35 <= xk_V_34;
        xk_V_36 <= xk_V_35;
        xk_V_37 <= xk_V_36;
        xk_V_38 <= xk_V_37;
        xk_V_39 <= xk_V_38;
        xk_V_40 <= xk_V_39;
        xk_V_41 <= xk_V_40;
        xk_V_42 <= xk_V_41;
        xk_V_43 <= xk_V_42;
        xk_V_44 <= xk_V_43;
        xk_V_45 <= xk_V_44;
        xk_V_46 <= xk_V_45;
        xk_V_47 <= xk_V_46;
        xk_V_48 <= xk_V_47;
        xk_V_49 <= xk_V_48;
        xk_V_50 <= xk_V_49;
        xk_V_51 <= xk_V_50;
        xk_V_52 <= xk_V_51;
        xk_V_53 <= xk_V_52;
        xk_V_54 <= xk_V_53;
        xk_V_55 <= xk_V_54;
        xk_V_56 <= xk_V_55;
        xk_V_57 <= xk_V_56;
        xk_V_58 <= xk_V_57;
        xk_V_59 <= xk_V_58;
        xk_V_60 <= xk_V_59;
        xk_V_61 <= xk_V_60;
        xk_V_62 <= xk_V_61;
        xk_V_7 <= xk_V_6_load_reg_3835;
        xk_V_8 <= xk_V_7;
        xk_V_9 <= xk_V_8;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_V_ap_vld = 1'b1;
    end else begin
        y_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign grp_fu_3271_p2 = {{tmp_2_fu_521_p4}, {18'd0}};

assign grp_fu_3280_p2 = {{tmp_4_fu_546_p4}, {18'd0}};

assign grp_fu_3289_p2 = {{tmp_5_fu_571_p4}, {18'd0}};

assign grp_fu_3298_p2 = {{tmp_9_fu_596_p4}, {18'd0}};

assign grp_fu_3315_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3315_p2 = {{lhs_V_2_fu_704_p1}, {20'd0}};

assign grp_fu_3324_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3324_p2 = {{lhs_V_2_1_fu_731_p1}, {20'd0}};

assign grp_fu_3333_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3333_p2 = {{lhs_V_2_2_fu_758_p1}, {20'd0}};

assign grp_fu_3342_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3342_p2 = {{lhs_V_2_3_fu_785_p1}, {20'd0}};

assign grp_fu_3351_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3351_p2 = {{lhs_V_2_4_fu_812_p1}, {20'd0}};

assign grp_fu_3360_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3360_p2 = {{lhs_V_2_5_fu_839_p1}, {20'd0}};

assign grp_fu_3369_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3369_p2 = {{lhs_V_2_6_fu_866_p1}, {20'd0}};

assign grp_fu_3378_p0 = r_V_1_cast_fu_696_p1;

assign grp_fu_3378_p2 = {{lhs_V_2_7_fu_893_p1}, {20'd0}};

assign grp_fu_3387_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3387_p2 = {{wk_V_8}, {20'd0}};

assign grp_fu_3395_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3395_p2 = {{wk_V_9}, {20'd0}};

assign grp_fu_3403_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3403_p2 = {{wk_V_10}, {20'd0}};

assign grp_fu_3411_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3411_p2 = {{wk_V_11}, {20'd0}};

assign grp_fu_3419_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3419_p2 = {{wk_V_12}, {20'd0}};

assign grp_fu_3427_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3427_p2 = {{wk_V_13}, {20'd0}};

assign grp_fu_3435_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3435_p2 = {{wk_V_14}, {20'd0}};

assign grp_fu_3443_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3443_p2 = {{wk_V_15}, {20'd0}};

assign grp_fu_3451_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3451_p2 = {{wk_V_16}, {20'd0}};

assign grp_fu_3459_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3459_p2 = {{wk_V_17}, {20'd0}};

assign grp_fu_3467_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3467_p2 = {{wk_V_18}, {20'd0}};

assign grp_fu_3475_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3475_p2 = {{wk_V_19}, {20'd0}};

assign grp_fu_3483_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3483_p2 = {{wk_V_20}, {20'd0}};

assign grp_fu_3491_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3491_p2 = {{wk_V_21}, {20'd0}};

assign grp_fu_3499_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3499_p2 = {{wk_V_22}, {20'd0}};

assign grp_fu_3507_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3507_p2 = {{wk_V_23}, {20'd0}};

assign grp_fu_3515_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3515_p2 = {{wk_V_24}, {20'd0}};

assign grp_fu_3523_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3523_p2 = {{wk_V_25}, {20'd0}};

assign grp_fu_3531_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3531_p2 = {{wk_V_26}, {20'd0}};

assign grp_fu_3539_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3539_p2 = {{wk_V_27}, {20'd0}};

assign grp_fu_3547_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3547_p2 = {{wk_V_28}, {20'd0}};

assign grp_fu_3555_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3555_p2 = {{wk_V_29}, {20'd0}};

assign grp_fu_3563_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3563_p2 = {{wk_V_30}, {20'd0}};

assign grp_fu_3571_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3571_p2 = {{wk_V_31}, {20'd0}};

assign grp_fu_3579_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3579_p2 = {{wk_V_32}, {20'd0}};

assign grp_fu_3587_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3587_p2 = {{wk_V_33}, {20'd0}};

assign grp_fu_3595_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3595_p2 = {{wk_V_34}, {20'd0}};

assign grp_fu_3603_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3603_p2 = {{wk_V_35}, {20'd0}};

assign grp_fu_3611_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3611_p2 = {{wk_V_36}, {20'd0}};

assign grp_fu_3619_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3619_p2 = {{wk_V_37}, {20'd0}};

assign grp_fu_3627_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3627_p2 = {{wk_V_38}, {20'd0}};

assign grp_fu_3635_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3635_p2 = {{wk_V_39}, {20'd0}};

assign grp_fu_3643_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3643_p2 = {{wk_V_40}, {20'd0}};

assign grp_fu_3651_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3651_p2 = {{wk_V_41}, {20'd0}};

assign grp_fu_3659_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3659_p2 = {{wk_V_42}, {20'd0}};

assign grp_fu_3667_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3667_p2 = {{wk_V_43}, {20'd0}};

assign grp_fu_3675_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3675_p2 = {{wk_V_44}, {20'd0}};

assign grp_fu_3683_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3683_p2 = {{wk_V_45}, {20'd0}};

assign grp_fu_3691_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3691_p2 = {{wk_V_46}, {20'd0}};

assign grp_fu_3699_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3699_p2 = {{wk_V_47}, {20'd0}};

assign grp_fu_3707_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3707_p2 = {{wk_V_48}, {20'd0}};

assign grp_fu_3715_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3715_p2 = {{wk_V_49}, {20'd0}};

assign grp_fu_3723_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3723_p2 = {{wk_V_50}, {20'd0}};

assign grp_fu_3731_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3731_p2 = {{wk_V_51}, {20'd0}};

assign grp_fu_3739_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3739_p2 = {{wk_V_52}, {20'd0}};

assign grp_fu_3747_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3747_p2 = {{wk_V_53}, {20'd0}};

assign grp_fu_3755_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3755_p2 = {{wk_V_54}, {20'd0}};

assign grp_fu_3763_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3763_p2 = {{wk_V_55}, {20'd0}};

assign grp_fu_3771_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3771_p2 = {{wk_V_56}, {20'd0}};

assign grp_fu_3779_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3779_p2 = {{wk_V_57}, {20'd0}};

assign grp_fu_3787_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3787_p2 = {{wk_V_58}, {20'd0}};

assign grp_fu_3795_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3795_p2 = {{wk_V_59}, {20'd0}};

assign grp_fu_3803_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3803_p2 = {{wk_V_60}, {20'd0}};

assign grp_fu_3811_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3811_p2 = {{wk_V_61}, {20'd0}};

assign grp_fu_3819_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3819_p2 = {{wk_V_62}, {20'd0}};

assign grp_fu_3827_p0 = r_V_1_cast_reg_3850;

assign grp_fu_3827_p2 = {{wk_V_63}, {20'd0}};

assign lhs_V_2_1_fu_731_p1 = wk_V_1;

assign lhs_V_2_2_fu_758_p1 = wk_V_2;

assign lhs_V_2_3_fu_785_p1 = wk_V_3;

assign lhs_V_2_4_fu_812_p1 = wk_V_4;

assign lhs_V_2_5_fu_839_p1 = wk_V_5;

assign lhs_V_2_6_fu_866_p1 = wk_V_6;

assign lhs_V_2_7_fu_893_p1 = wk_V_7;

assign lhs_V_2_fu_704_p1 = wk_V_0;

assign lhs_V_3_1_i_fu_472_p3 = {{tmp_fu_463_p4}, {18'd0}};

assign lhs_V_3_7_i_fu_630_p3 = {{tmp_10_fu_621_p4}, {18'd0}};

assign lhs_V_fu_656_p1 = $signed(dn_V);

assign r_V_1_cast_fu_696_p1 = $signed(r_V_fu_688_p3);

assign r_V_fu_688_p3 = {{ret_V_fu_682_p2}, {3'd0}};

assign ret_V_7_i_cast_fu_1485_p2 = ($signed(tmp_7_fu_1475_p1) + $signed(tmp_8_fu_1478_p3));

assign ret_V_7_i_fu_650_p2 = ($signed(lhs_V_3_7_i_fu_630_p3) + $signed(rhs_V_7_i_cast_fu_638_p1));

assign ret_V_fu_682_p2 = ($signed(lhs_V_fu_656_p1) - $signed(rhs_V_1_cast_fu_678_p1));

assign rhs_V_1_cast_fu_678_p1 = $signed(rhs_V_fu_670_p3);

assign rhs_V_7_i_cast_fu_638_p1 = r_V_5_7_i_fu_3308_p2;

assign rhs_V_fu_670_p3 = {{tmp_12_fu_660_p4}, {2'd0}};

assign tmp_10_fu_621_p4 = {{grp_fu_3298_p3[31:18]}};

assign tmp_12_fu_660_p4 = {{ret_V_7_i_fu_650_p2[31:18]}};

assign tmp_13_fu_3227_p4 = {{ret_V_7_i_cast_fu_1485_p2[30:18]}};

assign tmp_1_fu_501_p3 = {{tmp_3_fu_484_p4}, {18'd0}};

assign tmp_2_fu_521_p4 = {{grp_fu_3262_p3[31:18]}};

assign tmp_3_fu_484_p4 = {{grp_fu_3253_p3[30:18]}};

assign tmp_4_fu_546_p4 = {{grp_fu_3271_p3[31:18]}};

assign tmp_5_fu_571_p4 = {{grp_fu_3280_p3[31:18]}};

assign tmp_7_fu_1475_p1 = r_V_5_7_i_reg_3840;

assign tmp_8_fu_1478_p3 = {{tmp_11_reg_3845}, {18'd0}};

assign tmp_9_fu_596_p4 = {{grp_fu_3289_p3[31:18]}};

assign tmp_fu_463_p4 = {{r_V_5_i_fu_3246_p2[29:18]}};

assign y_V = {{tmp_13_fu_3227_p4}, {1'd0}};

always @ (posedge ap_clk) begin
    r_V_1_cast_reg_3850[2:0] <= 3'b000;
end

endmodule //lms
