# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/lms_0_5/lms_0.xci
# IP: The module: 'lms_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/lms_0_5/constraints/lms_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lms_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/lms_0_5/lms_0.xci
# IP: The module: 'lms_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_2018/Vivado/LMS/LMS.srcs/sources_1/ip/lms_0_5/constraints/lms_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lms_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
